TITLE = "Solving ARC-AGI-3 with Code World Models"
SUBTITLE = "First time all 25 games were solved without ever reading the game's code: the agent writes a little program that copies the game's rules, then figures out how to win"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The whole talk on one map"},
    {"type": "part", "title": "The problem", "subtitle": "What ARC-AGI-3 is, and why it is hard"},
    {"type": "bullets", "title": "Puzzles you can only crack by playing",
     "bullets": [
         "Older ARC puzzles: look at a before-and-after grid and spot the pattern",
         "ARC-AGI-3: little video-game puzzles where you learn the rules and the goal only by playing",
         "Each game: a 64x64 grid of dots, 16 colors, 6 to 10 levels",
         "Tests exploring, learning how things move, guessing the goal, and planning",
         "On purpose: no words, no outside knowledge -- just the screen"]},
    {"type": "figure", "title": "A real example: the game ka59",
     "image": "figs/arc3_example_ka59.png",
     "caption": "Two rooms, a hallway, a purple door: walk over, then click to clear the level",
     "bullets": [
         "The agent is told nothing: no rules, no goal in words",
         "You can move (buttons 1-5,7) or click a spot on the grid (ACTION6)",
         "Winning is a set of steps in the right order, not one good screen"]},
    {"type": "bullets", "title": "Why it is hard",
     "bullets": [
         "People solve every one of these games; 100%",
         "The best AI agents scored under 1% (March 2026)",
         "No instructions; you have to discover how to win on your own",
         "A win takes many steps, and you get nothing until the very end"]},
    {"type": "statement",
     "text": "The hard part is not copying how the game works. It is figuring out what you are supposed to be doing."},

    {"type": "part", "title": "The recipe", "subtitle": "Write a rule-copy program by playing, and keep checking it"},
    {"type": "flow", "title": "The loop, in six steps",
     "steps": ["Look", "Explore", "Write the rules", "Guess the goal", "Plan", "Check"],
     "icons": ["eye", "compass", "code", "target", "branch", "check"]},
    {"type": "figure", "title": "How the agent solves a game",
     "image": "figs/arc3_architecture.png",
     "caption": "Look -> explore -> write the rules as code -> guess the goal -> plan -> re-play the moves to prove it works",
     "bullets": [
         "Kept in a locked box that never reads the game's code",
         "Turns the picture into simple facts about what is on the screen",
         "Every solve becomes a working world you can open and play"]},
    {"type": "bullets", "title": "The loop, in plain words",
     "bullets": [
         "Poke around: act, and write down 'from this screen, this button gave that screen'",
         "Write the rule as code: the AI writes a little program that predicts the next screen",
         "Keep it only if it gets examples it had not seen exactly right (check 1)",
         "Guess the goal: what makes the level counter go up?",
         "Plan inside the program, then re-play the moves against the real game to prove it (check 2)"]},
    {"type": "figure", "title": "What a world model is made of",
     "image": "figs/arc3_anatomy.png",
     "caption": "The copy of a game is itself a little world -- same five parts, and worlds fit inside worlds",
     "bullets": [
         "Where things are, what you can do, how it changes, what you see, what counts as good",
         "Copying a game means building a world whose changes match the real one",
         "A world can hold another world inside it"]},

    {"type": "section", "title": "Copying the game is not the wall"},
    {"type": "bullets", "title": "The copy of the game is just code",
     "bullets": [
         "The games repeat perfectly: same move, same result, every time (score 1.00)",
         "So the rules can be written out exactly, as Python code",
         "A program is kept only if it gets unseen examples exactly right",
         "Claude: on 21 changing games, it got the whole next screen right 49% of the time",
         "3 were nearly perfect; small local models got almost nothing"]},
    {"type": "figure", "title": "How well each model copies the rules",
     "image": "figs/arc3_fidelity.png",
     "caption": "Claude rewrites the game's rules as working code far better than the small local models",
     "bullets": [
         "One wrong dot in the 64x64 screen and it fails the check",
         "The smarter model wins big: qwen-32B and qwen-7B are far behind",
         "This only tests next-screen accuracy -- no games are won here, on purpose"]},
    {"type": "statement",
     "text": "The rules can be copied exactly, as checked code. Building the copy of the game is the easy half."},

    {"type": "part", "title": "The wall", "subtitle": "A win is a recipe of steps in order, not one good screen"},
    {"type": "anim", "diagram": "procedure", "title": "One good screen vs a recipe of steps",
     "still": "figs/arc3_goal_as_procedure.png"},
    {"type": "bullets", "title": "Four careful ways to guess the goal -- all fail",
     "bullets": [
         "Try simple goals (get here / cover this / collect that): 0",
         "Ask a top AI to guess the goal, with and without feedback: 0",
         "Reason about goals across the nested sub-worlds: 0",
         "Rebuild the game engine from play and prove a goal: 0",
         "All win 0 of the hard games -- even when handed a perfect copy of the rules"]},
    {"type": "bullets", "title": "Why guessing the goal by machine cannot cross it",
     "bullets": [
         "Exploring only touches a tiny corner (50-138 screens) and never trips the reward",
         "One-shot guesses miss: on s5i5, it thinks a timer is the goal",
         "Adding feedback does not help: it only says 'wrong', never 'warmer'",
         "A huge cold brute-force sweep (E146): 0 new games won this way",
         "The stuck point is guessing the goal -- not copying, planning, or exploring"]},
    {"type": "statement",
     "text": "A copy of the game is useless until it holds a proven path to the win. Exploring more of the game does not help."},

    {"type": "section", "title": "The landscape of approaches"},
    {"type": "figure", "title": "Which approach solves which game",
     "image": "figs/arc3_strategy_heatmap.png",
     "caption": "The goal-guessing columns are empty; only the reasoning agent lights up the hard games",
     "bullets": [
         "Directed search and map-building each solve 6 games",
         "Combining several ways of seeing reaches 10 (best of the automatic tiers)",
         "The live coding agent lights up the recipe-walls nothing else can touch"]},
    {"type": "cards", "title": "Three kinds of approach",
     "cards": [
         {"head": "Guess the goal", "icon": "target", "text": "All fail -- 0 hard games, even with a perfect copy"},
         {"head": "Seeing and searching", "icon": "compass", "text": "Only games you can stumble into"},
         {"head": "Reasoning agent", "icon": "gear", "text": "The only way that crosses the walls"}]},
    {"type": "bullets", "title": "The reasoning agent that writes its own copy of the game",
     "bullets": [
         "Claude Code: one working session per game, no trying over and over",
         "The prompt gives only the controls and the recipe -- never how to win",
         "On its own the live agent solves 15 of 25 games",
         "Crosses every wall the automatic ways miss (dc22, g50t, ka59, ...)",
         "Reasons out the goal instead of searching a fixed list of guesses"]},

    {"type": "part", "title": "Results", "subtitle": "All 25 solved, a stronger model solves more, and the atlas"},
    {"type": "stats", "title": "The first time every game was solved this way",
     "items": [{"value": "25/25", "label": "games, no code read", "hi": True, "icon": "grid"},
               {"value": "183/183", "label": "levels solved", "icon": "stack"},
               {"value": "1st", "label": "perfect run", "icon": "check"}]},
    {"type": "figure", "title": "Every game solved, one by one (a stronger model solves more)",
     "image": "figs/arc3_source_matrix.png",
     "caption": "Claude Fable clears all 25 games; a stronger model clears more walls for the same budget",
     "bullets": [
         "Claude Fable 5: 25/25 games, 183/183 levels -- the first perfect run",
         "Main run Claude Opus 4.8: 16/25 (158 levels) on the exact same setup",
         "GPT-5.5: 12/25; best earlier work (baseline1): 15/25 (145 levels)",
         "All proven by re-playing the moves; none use stored answers"]},
    {"type": "bullets", "title": "The headline numbers, read carefully",
     "bullets": [
         "Fable 25/25 with no code read, done 2026-07-04 09:05:14 UTC",
         "Beats the earlier best on games, levels, and how few moves it used",
         "Clears lf52's last level -- the one level no earlier run ever solved",
         "Every solved game is a real world you can run, open, and play",
         "Public games only; the private hidden set was not touched"]},
    {"type": "figure", "title": "A stronger model clears more walls",
     "image": "figs/pres_arc3_scaling.png",
     "caption": "Same setup, same prompt, same budget -- only the model changes",
     "bullets": [
         "GPT-5.5 12 -> Opus 16 -> Fable 25 of 25 games",
         "Fable finds each solve using about 3.5x less text (23M vs 81M)"]},
    {"type": "figure", "title": "How few moves it used, per level (Fable, no code read)",
     "image": "figs/arc3_rhae.png",
     "caption": "Every game matches or beats a person; per-level score min((b/a)^2 * 100, 115)",
     "bullets": [
         "Fable used far fewer moves than a person: score 100.0 vs the earlier best's 58 (~72% better)",
         "174 of 183 levels beat the person; 168 hit the top score of 115",
         "Moves per level are usually about a third of a person's",
         "Scored by the game's own tool -- we did not rebuild the measure"]},
    {"type": "figure", "title": "An honest baseline: levels reached vs random play",
     "image": "figs/arc3_above_random.png",
     "caption": "Random play reaches the first level of 11/25, but finishes 0 games all the way",
     "bullets": [
         "With unlimited free restarts offline, about half the 'reached one level' count is free",
         "One 'solve' (lp85, one click over and over) is no better than random",
         "What really counts: 14 games random never even reaches (the walls)",
         "So we report 16/25 as clearly better than random"]},

    {"type": "section", "title": "The atlas: every solve is a world"},
    {"type": "figure", "title": "25 games, 25 working worlds you can open",
     "image": "figs/arc3_maps_gallery.png",
     "caption": "A winning screen from Fable's from-scratch solve of every game",
     "bullets": [
         "Each solve: turn the picture into facts -> a rules program -> a goal check",
         "Saves as a one-page atlas card, and runs at openworld serve /view",
         "25 clearly different worlds: moving, clicking, box-pushing, mirrors, building"]},
    {"type": "figure", "title": "Example solve: ka59 (7/7)",
     "image": "figs/arc3_replay_ka59.png",
     "caption": "The world-model card (top) plus the level-by-level replay (bottom)",
     "bullets": [
         "The card's map is the path through the levels, with each step's button on it",
         "The replay: real screenshots at each level clear, re-run against the game"]},
    {"type": "figure", "title": "Example solve: dc22 (6/6) -- a recipe wall",
     "image": "figs/arc3_replay_dc22.png",
     "caption": "Mixes moving and clicking; only the reasoning agent crosses it",
     "bullets": [
         "Random play never even reaches level 1 here",
         "A key-and-box routine slides a movable structure into place"]},
    {"type": "figure", "title": "Example solve: g50t (7/7) -- ghost-switch",
     "image": "figs/arc3_replay_g50t.png",
     "caption": "A big 94-spot map never proves a win on its own -- reasoning is what does it",
     "bullets": [
         "Hold-down plates, toggle buttons, warp rings, a pinball ghost that copies you",
         "The value is the proven winning chain, not how big the map is"]},
    {"type": "figure", "title": "The last wall: lf52 (10/10)",
     "image": "figs/arc3_replay_lf52.png",
     "caption": "The one level no run had ever solved -- a proven 914-move path",
     "bullets": [
         "Cracked with a keep-your-notes deep-wall routine",
         "Build a proven copy of the level, then search it offline at full scale",
         "Solving it completed the perfect 25/25 sweep"]},
    {"type": "figure", "title": "Example solve: su15 (9/9) -- merge and deliver",
     "image": "figs/arc3_replay_su15.png",
     "caption": "Click to gather; matching tiers merge and grow; a 141-click solution",
     "bullets": [
         "The clickable targets were figured out from the pixels alone",
         "Runs as a real, openable OpenWorld world"]},

    {"type": "section", "title": "How the models actually solve (the play-by-play)"},
    {"type": "figure", "title": "The shape of a solve",
     "image": "figs/e150_cardiogram.png",
     "caption": "Read/Write-heavy start (building) -> Bash-heavy middle (searching) -> Edit fixes",
     "bullets": [
         "Levels get cleared in sudden jumps, not steady progress",
         "Build first, then search -- the same shape in every solve"]},
    {"type": "figure", "title": "The words each game made the agent invent",
     "image": "figs/e150_concepts.png",
     "caption": "The names the agent chose in its code recover each game's mechanics, with no help",
     "bullets": [
         "ka59 -> box/push/ring (box-pushing); ft09 -> blk/slots (stencil)",
         "The ideas the agent had to invent tell you what kind of puzzle it was"]},
    {"type": "figure", "title": "The signature of each solution",
     "image": "figs/e150_signatures.png",
     "caption": "Each winning path as a strip of moves: clicks, moving, or a mix",
     "bullets": [
         "Ochre = click (ACTION6); blue = moving (1-5,7)",
         "A picture-map of each solution's shape and length (lf52 is longest)"]},
    {"type": "figure", "title": "Where the agent clicked",
     "image": "figs/e150_clicks.png",
     "caption": "How thick the winning clicks land on the 64x64 board -- no hidden list of targets",
     "bullets": [
         "The clickable spots the agent figured out from the pixels alone",
         "opus looks harder at the picture; Fable leans on memory plus checking"]},

    {"type": "part", "title": "Reflection", "subtitle": "Honest limits and what comes next"},
    {"type": "bullets", "title": "It is the best of many tries; a single try is not reliable",
     "bullets": [
         "Each solve is the proven best of many tries, not one lucky shot",
         "About 823 sessions across 25 games (about 33 per game)",
         "A full win on about 6% of tries overall, as low as about 2% on bp35/lf52",
         "A clean fixed-prompt, many-seed test (more than 1) is a clear next step"]},
    {"type": "bullets", "title": "We cannot yet measure if the model saw these games in training",
     "bullets": [
         "We check that no run reads the game's code -- measured every run",
         "But we cannot rule out a public game already sitting in the model's memory",
         "This applies to every top-model result, the earlier best included",
         "Quick check: Fable knew 0/25 games from the name alone (not proof)"]},
    {"type": "bullets", "title": "Offline, unlimited restarts, one run",
     "bullets": [
         "All solves are offline, with unlimited restarts and perfect replay",
         "Not the live leaderboard, which docks you for extra moves",
         "A fresh fair-budget result; a repeat or a live run might change it",
         "The cost is a rough guess; the perfect run was not the cheap one"]},

    {"type": "section", "title": "Conclusion"},
    {"type": "bullets", "title": "What we showed",
     "bullets": [
         "First perfect ARC-AGI-3 result, and no code was ever read: Fable 25/25",
         "Copying the game is not the wall -- the rules can be written out as code",
         "The real wall is the win being a recipe of steps: one-screen scoring wins 0",
         "Only a reasoning agent that writes its own copy of the game crosses it",
         "A stronger model carries it from 16/25 to solving every game"]},
    {"type": "bullets", "title": "The takeaway for builders",
     "bullets": [
         "In these games a win is a recipe of steps in order, not one good screen",
         "Any one-screen score fails, even with a perfect copy of the game",
         "Aim at finding the recipe, not at scoring screens",
         "Every solver is an open, replay-proven, runnable world",
         "Next: live-run efficiency, many-seed spread, a training-memory-controlled test"]},
    {"type": "statement",
     "text": "The recipe of steps is the wall. Reasoning is the ladder. Every solve downloads, re-runs, and opens as a world."},
]
