TITLE = "Solving ARC-AGI-3 with Code World Models"
SUBTITLE = "First perfect source-free result: 25/25 games — a source-free agent writes a verified world model, then reasons the win"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The talk in one map"},
    {"type": "part", "title": "The problem", "subtitle": "What is ARC-AGI-3 — and why it is hard"},
    {"type": "bullets", "title": "The interactive reasoning frontier",
     "bullets": [
         "ARC-AGI-1/-2: abstraction from static input-output grids",
         "ARC-AGI-3: interactive games; rules and goals revealed only by acting",
         "Each game: a 64x64 grid, 16 colors, 6-10 levels",
         "Isolates exploration, dynamics modeling, goal-setting, planning",
         "By design avoids language and external knowledge"]},
    {"type": "figure", "title": "A worked example: the game ka59",
     "image": "figs/arc3_example_ka59.png",
     "caption": "Two rooms, a corridor, a purple door: navigate then click to clear the level",
     "bullets": [
         "Agent is told nothing: no rules, no goal in words",
         "Actions are directional (1-5,7) or a coordinate click (ACTION6)",
         "The win is an ordered procedure, not a single reachable state"]},
    {"type": "bullets", "title": "Why it is hard",
     "bullets": [
         "Human-calibrated: people solve 100% of environments",
         "Frontier LLM agents score below 1% (March 2026)",
         "No instructions; the win condition must be discovered",
         "Wins span many steps with no reward until the end"]},
    {"type": "statement",
     "text": "The hard part is not modeling the game -- it is figuring out what you are trying to do."},

    {"type": "part", "title": "The recipe", "subtitle": "A verified code world model, built by acting"},
    {"type": "flow", "title": "The loop, in six steps",
     "steps": ["Perceive", "Explore", "Synthesize", "Reason goal", "Plan", "Verify"],
     "icons": ["eye", "compass", "code", "target", "branch", "check"]},
    {"type": "figure", "title": "How the agent solves a game",
     "image": "figs/arc3_architecture.png",
     "caption": "Perceive -> explore -> synthesize verified code -> reason goal -> plan -> replay-verify",
     "bullets": [
         "Process-isolated behind a source-free boundary (never reads game code)",
         "Masked-frame perceptor maps pixels to a symbolic state",
         "Each solve becomes a serveable OpenWorld World"]},
    {"type": "bullets", "title": "The loop, in plain steps",
     "bullets": [
         "Look around: gather (state, action, next-state) facts by acting",
         "Write the rule as code: an LLM writes predict(frame, action)",
         "Keep it only if it exact-matches held-out transitions (gate 1)",
         "Reason the goal: what raises levels_completed?",
         "Plan inside the code, then replay-verify on the real engine (gate 2)"]},
    {"type": "figure", "title": "Anatomy of a world model",
     "image": "figs/arc3_anatomy.png",
     "caption": "The model of a world is itself a World -- same five parts, and worlds nest",
     "bullets": [
         "State, actions, transition, perception, reward",
         "Modeling = building a World whose transition reproduces the game",
         "CompositeWorld = a world inside a world"]},

    {"type": "section", "title": "Modeling is not the binding wall"},
    {"type": "bullets", "title": "The world model IS code",
     "bullets": [
         "Games are perfectly repeatable: determinism = 1.00",
         "So the rules can be written down exactly as Python",
         "A program is banked only if it exact-matches held-out transitions",
         "Claude: 49% single-step exact-match on 21 changing games",
         "3 near-perfect; small local models get almost nothing"]},
    {"type": "figure", "title": "Verified-code fidelity by model",
     "image": "figs/arc3_fidelity.png",
     "caption": "Claude re-writes the game's rules as working code far better than local models",
     "bullets": [
         "One wrong cell in the 64x64 frame fails the check",
         "Capability dominates: qwen-32B and qwen-7B are far behind",
         "This is single-step fidelity -- 0 games are solved here, by design"]},
    {"type": "statement",
     "text": "The dynamics are exactly recoverable as verified code. Building the copy of the game is the easy half."},

    {"type": "part", "title": "The wall", "subtitle": "Wins are ordered procedures, not states"},
    {"type": "anim", "diagram": "procedure", "title": "Goal-as-state vs goal-as-procedure",
     "still": "figs/arc3_goal_as_procedure.png"},
    {"type": "bullets", "title": "Four principled goal-discovery methods -- all fail",
     "bullets": [
         "Atomic candidate-goal objectives (reach/cover/collect): 0",
         "Frontier-LLM goal hypotheses, open- and closed-loop: 0",
         "Bayesian active inference over composite sub-worlds: 0",
         "Source-free engine reconstruction + certificate: 0",
         "All solve 0 hard games -- even handed a perfect (fidelity-1.0) model"]},
    {"type": "bullets", "title": "Why automated goal discovery cannot cross it",
     "bullets": [
         "Exploration saturates a tiny region (50-138 states), triggers 0 reward",
         "One-shot goal guesses: on s5i5, a timer is mistaken for the objective",
         "Closing the loop fails: negative feedback says wrong, not right",
         "E146 exhaustive cold-search battery: 0 new source-free levels",
         "The bottleneck is goal inference, not modeling/planning/coverage"]},
    {"type": "statement",
     "text": "A world model is worthless until it contains a verified, win-terminating path -- breadth of exploration does not help."},

    {"type": "section", "title": "The strategy landscape"},
    {"type": "figure", "title": "Strategy x game: what solves what",
     "image": "figs/arc3_strategy_heatmap.png",
     "caption": "Goal-discovery columns are empty; only the reasoning agent lights the walls",
     "bullets": [
         "Directed search and graph exploration each reach 6 games",
         "Multi-perception consensus reaches 10 (best automated tier)",
         "The live coding agent lights up the procedural walls no method touches"]},
    {"type": "cards", "title": "Three categories of approach",
     "cards": [
         {"head": "Goal-discovery", "icon": "target", "text": "All fail — 0 walls, even on a perfect model"},
         {"head": "Perception & search", "icon": "compass", "text": "Reachable games only"},
         {"head": "Reasoning agent", "icon": "gear", "text": "The only method that crosses the walls"}]},
    {"type": "bullets", "title": "The reasoning agent that writes its own world model",
     "bullets": [
         "Claude Code: one agentic session per game, no repeated sampling",
         "Prompt gives only the harness API and recipe -- not the win condition",
         "On its own the live agent solves 15/25 games",
         "Crosses every wall the automated methods miss (dc22, g50t, ka59, ...)",
         "Reasons the goal rather than searching a fixed hypothesis space"]},

    {"type": "part", "title": "Results", "subtitle": "Source-free completion, model-scaling, the atlas"},
    {"type": "stats", "title": "The first perfect source-free result",
     "items": [{"value": "25/25", "label": "games, source-free", "hi": True, "icon": "grid"},
               {"value": "183/183", "label": "levels solved", "icon": "stack"},
               {"value": "1st", "label": "perfect result", "icon": "check"}]},
    {"type": "figure", "title": "Source-free completion, per game (a model-scaling result)",
     "image": "figs/arc3_source_matrix.png",
     "caption": "Claude Fable sweeps all 25 games; a stronger model clears more walls at equal budget",
     "bullets": [
         "Claude Fable 5: 25/25 games, 183/183 levels -- the first perfect result",
         "Primary Claude Opus 4.8: 16/25 (158 levels) on the identical harness",
         "GPT-5.5: 12/25; prior best baseline1: 15/25 (145 levels)",
         "All replay-verified; none use banked solutions"]},
    {"type": "bullets", "title": "The headline numbers, read carefully",
     "bullets": [
         "Fable 25/25 source-free, achieved 2026-07-04 09:05:14 UTC",
         "Beats baseline1 on games, levels, and efficiency",
         "Clears lf52's final level -- the one level no earlier run solved",
         "Every solved game is a runnable, serveable OpenWorld World",
         "Public games only; private held-out set not accessed"]},
    {"type": "figure", "title": "Model scaling: a stronger model clears more walls",
     "image": "figs/pres_arc3_scaling.png",
     "caption": "Same harness, prompt, and budget -- only the model changes",
     "bullets": [
         "GPT-5.5 12 -> Opus 16 -> Fable 25 of 25 games",
         "Fable finds each solve in ~3.5x fewer tokens (23M vs 81M)"]},
    {"type": "figure", "title": "Action efficiency, per level (source-free, Fable)",
     "image": "figs/arc3_rhae.png",
     "caption": "Every game at or above the human baseline; per-level score min((b/a)^2 * 100, 115)",
     "bullets": [
         "Fable per-game RHAE 100.0 vs baseline1's 58 (~72% more efficient)",
         "174/183 levels beat the human; 168 hit the 115 cap",
         "Action count per level is typically about a third of the human's",
         "Scored with arc_agi's own calculator -- no metric re-implemented"]},
    {"type": "figure", "title": "Honest baseline: levels reached vs random play",
     "image": "figs/arc3_above_random.png",
     "caption": "Random reaches 11/25 first levels but completes 0 games in full",
     "bullets": [
         "Under offline unbounded resets, ~half the >=1-level metric is free",
         "One agent 'solve' (lp85, a repeated click) is no better than random",
         "Distinctive value: 14 games random never reaches (the walls)",
         "We report 16/25 strictly above random"]},

    {"type": "section", "title": "The atlas: every solve is a world"},
    {"type": "figure", "title": "25 games, 25 verified serveable world models",
     "image": "figs/arc3_maps_gallery.png",
     "caption": "A solved-board frame from Fable's source-free solve of every game",
     "bullets": [
         "Each solve = masked-frame perceptor -> FunctionTransition -> CodeObjective",
         "Serializes to a self-contained atlas card, serves at openworld serve /view",
         "25 visibly distinct worlds: directional, click, sokoban, mirror, synthesis"]},
    {"type": "figure", "title": "Example solve: ka59 (7/7)",
     "image": "figs/arc3_replay_ka59.png",
     "caption": "The discovered world-model card (top) + the level-completion replay (bottom)",
     "bullets": [
         "Card graph = the level trajectory, edges labelled by button-presses",
         "Replay = real screenshots at each level clear, re-run against the game"]},
    {"type": "figure", "title": "Example solve: dc22 (6/6) -- a procedural wall",
     "image": "figs/arc3_replay_dc22.png",
     "caption": "Interleaves moves and clicks; only the reasoning agent crosses it",
     "bullets": [
         "Random never reaches level 1 here",
         "A keybox-to-bridge protocol relocates a movable structure"]},
    {"type": "figure", "title": "Example solve: g50t (7/7) -- ghost-switch",
     "image": "figs/arc3_replay_g50t.png",
     "caption": "A rich 94-node search graph terminates in no verified win without reasoning",
     "bullets": [
         "Hold-plates, toggle-buttons, ring-warps, a pinball ghost echo",
         "The value is the win-terminating chain, not the map's breadth"]},
    {"type": "figure", "title": "The final wall: lf52 (10/10)",
     "image": "figs/arc3_replay_lf52.png",
     "caption": "The single level no run had solved -- a 914-action verified path",
     "bullets": [
         "Fell to a persistent-workspace deep-wall protocol",
         "Build a verified simulator of the level, then search it offline at scale",
         "Its solve completed the perfect 25/25 sweep"]},
    {"type": "figure", "title": "Example solve: su15 (9/9) -- merge and deliver",
     "image": "figs/arc3_replay_su15.png",
     "caption": "Click-gather tiers merge and escalate; a 141-click solution",
     "bullets": [
         "Sprite click targets inferred from pixels alone",
         "Round-trips through an OpenWorld World"]},

    {"type": "section", "title": "How the models actually solve (run lineages)"},
    {"type": "figure", "title": "Anatomy of a solve",
     "image": "figs/e150_cardiogram.png",
     "caption": "Read/Write-heavy start (build) -> Bash-heavy middle (search) -> Edit repairs",
     "bullets": [
         "Level-ups fall as punctuated events, not steady progress",
         "Modeling then search -- the shared shape of every solve"]},
    {"type": "figure", "title": "The vocabulary each game forces the agent to invent",
     "image": "figs/e150_concepts.png",
     "caption": "Code identifiers the agent writes recover each game's mechanics unsupervised",
     "bullets": [
         "ka59 -> box/push/ring (sokoban); ft09 -> blk/slots (stencil)",
         "The concepts an agent had to invent characterize the solution class"]},
    {"type": "figure", "title": "Solution signatures",
     "image": "figs/e150_signatures.png",
     "caption": "Every banked path as an action strip: click, directional, or mixed",
     "bullets": [
         "Ochre = click ACTION6; blue = directional 1-5,7",
         "A visual taxonomy of solution shape and length (lf52 longest)"]},
    {"type": "figure", "title": "Inferred click targets",
     "image": "figs/e150_clicks.png",
     "caption": "Density of banked click coordinates on the 64x64 board -- no privileged target list",
     "bullets": [
         "The sprite targets the agent inferred from pixels alone",
         "opus is perception-heavy; Fable leans on memory recall + verification"]},

    {"type": "part", "title": "Reflection", "subtitle": "Honest limitations & what comes next"},
    {"type": "bullets", "title": "Best-of-N; single-attempt reliability is low",
     "bullets": [
         "Each solve is the verified best of many attempts, not a single draw",
         "~823 sessions across 25 games (mean ~33/game)",
         "Full wins on ~6% of attempts overall, as low as ~2% on bp35/lf52",
         "Clean fixed-prompt, multi-seed variance (N>1) is a labeled next step"]},
    {"type": "bullets", "title": "Training-memory contamination is unmeasured",
     "bullets": [
         "The protocol audits no runtime source read -- it is measured per run",
         "It cannot rule out a public game sitting in the model's weights",
         "This channel affects every frontier-model result, prior SOTA included",
         "Quick check: Fable recognised 0/25 games from ID alone (not proof)"]},
    {"type": "bullets", "title": "Offline, unbounded resets, N=1",
     "bullets": [
         "All solves computed offline with unbounded resets, deterministic replay",
         "Not the leaderboard's live action-efficiency penalty",
         "A fresh fair-budget result; a repeat or live run may revise it",
         "Cost is an uncontrolled estimate; the perfect run was not the cheap one"]},

    {"type": "section", "title": "Conclusion"},
    {"type": "bullets", "title": "What we showed",
     "bullets": [
         "First perfect ARC-AGI-3 result, and it is source-free: Fable 25/25",
         "Modeling is not the wall -- dynamics are exactly writable as code",
         "The true wall is goal-as-procedure: state-scoring banks 0",
         "Only a reasoning agent that writes its own world model crosses it",
         "Model scale carries completion from 16/25 to the full sweep"]},
    {"type": "bullets", "title": "The transferable lesson for builders",
     "bullets": [
         "Interactive-reasoning wins are ordered procedures, not good screens",
         "Any single-state score fails even on a perfect model",
         "Aim at procedure discovery, not state scoring",
         "Every solver is an open, replay- and OpenWorld-verified World",
         "Next: live-protocol RHAE, N>1 variance, contamination-controlled model"]},
    {"type": "statement",
     "text": "Goal-as-procedure is the wall. Reasoning is the ladder. Every solve downloads, re-runs, and serves as a world."},
]
