TITLE = "Solving ARC-AGI-3 with Code World Models"
SUBTITLE = "First time all 25 games were solved without ever reading the game's code: the agent writes a little program that copies the game's rules, then figures out how to win"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The whole talk on one map"},
    {"type": "part", "title": "The problem", "subtitle": "What ARC-AGI-3 is, and why it is hard"},
    {"type": "compare", "title": "Puzzles you can only crack by playing",
     "left": {"head": "Old ARC", "icon": "grid",
              "items": ["Look at a before-and-after grid",
                        "Spot the pattern"]},
     "right": {"head": "ARC-AGI-3", "icon": "eye",
               "items": ["Little video-game puzzles: learn the rules and the goal only by playing",
                         "A 64x64 grid of dots, 16 colors, 6 to 10 levels",
                         "Screen only: no words, no outside knowledge",
                         "Tests exploring, learning how things move, guessing the goal, and planning"]}},
    {"type": "figure", "title": "A real example: the game ka59",
     "image": "figs/arc3_example_ka59.png",
     "caption": "Two rooms, a hallway, a purple door: walk over, then click to clear the level",
     "bullets": [
         "The agent is told nothing: no rules, no goal in words",
         "You can move (buttons 1-5,7) or click a spot on the grid (ACTION6)",
         "Winning is a set of steps in the right order, not one good screen"]},
    {"type": "bigstat", "title": "Why it is hard",
     "value": "<1%", "sub": "best AI scored, March 2026",
     "points": ["People solve every one of these games -- 100%",
                "No instructions: you discover how to win on your own",
                "A win takes many steps, and you get nothing until the very end"]},
    {"type": "statement",
     "text": "The hard part is not copying how the game works. It is figuring out what you are supposed to be doing."},

    {"type": "part", "title": "The recipe", "subtitle": "Write a rule-copy program by playing, and keep checking it"},
    {"type": "flow", "title": "The loop, in six steps",
     "steps": ["Look", "Explore", "Write the rules", "Guess the goal", "Plan", "Check"],
     "icons": ["eye", "compass", "code", "target", "branch", "check"]},
    {"type": "figure", "title": "How the agent solves a game",
     "image": "figs/arc3_architecture.png",
     "caption": "Look -> explore -> write the rules as code -> guess the goal -> plan -> re-play the moves to prove it works",
     "bullets": [
         "Kept in a locked box that never reads the game's code",
         "Turns the picture into simple facts about what is on the screen",
         "Every solve becomes a working world you can open and play"]},
    {"type": "steps", "title": "The loop, in plain words",
     "steps": [
         {"head": "Poke around", "text": "Act, and note 'from this screen, this button gave that screen'"},
         {"head": "Write the rule", "text": "A little program predicts the next screen; keep it only if unseen examples come out exactly right (check 1)"},
         {"head": "Guess the goal", "text": "What makes the level counter go up?"},
         {"head": "Plan and prove", "text": "Plan inside the program, then re-play the moves against the real game (check 2)"}]},
    {"type": "figure", "title": "What a world model is made of",
     "image": "figs/arc3_anatomy.png",
     "caption": "The copy of a game is itself a little world -- same five parts, and worlds fit inside worlds",
     "bullets": [
         "Where things are, what you can do, how it changes, what you see, what counts as good",
         "Copying a game means building a world whose changes match the real one",
         "A world can hold another world inside it"]},

    {"type": "section", "title": "Copying the game is not the wall"},
    {"type": "quadrant", "title": "The copy of the game is just code",
     "cells": [
         {"head": "Repeatable", "icon": "check", "text": "Same move, same result, every time (score 1.00)"},
         {"head": "Written as code", "icon": "code", "text": "So the rules can be written out exactly, as Python"},
         {"head": "Only if passes", "icon": "shield", "text": "A program is kept only if it gets unseen examples exactly right"},
         {"head": "Claude 49%", "icon": "gauge", "text": "On 21 changing games, got the whole next screen right 49% of the time; 3 nearly perfect, small local models almost nothing"}]},
    {"type": "figure", "title": "How well each model copies the rules",
     "image": "figs/arc3_fidelity.png",
     "caption": "Claude rewrites the game's rules as working code far better than the small local models",
     "bullets": [
         "One wrong dot in the 64x64 screen and it fails the check",
         "The smarter model wins big: qwen-32B and qwen-7B are far behind",
         "This only tests next-screen accuracy -- no games are won here, on purpose"]},
    {"type": "statement",
     "text": "The rules can be copied exactly, as checked code. Building the copy of the game is the easy half."},

    {"type": "part", "title": "The wall", "subtitle": "A win is a recipe of steps in order, not one good screen"},
    {"type": "anim", "diagram": "procedure", "title": "One good screen vs a recipe of steps",
     "still": "figs/arc3_goal_as_procedure.png"},
    {"type": "quadrant", "title": "Four careful ways to guess the goal -- all fail (0), even with a perfect copy of the rules",
     "cells": [
         {"head": "Simple goals", "icon": "target", "text": "Get here / cover this / collect that: 0"},
         {"head": "Ask top AI", "icon": "gear", "text": "Guess the goal, with and without feedback: 0"},
         {"head": "Nested worlds", "icon": "nested", "text": "Reason about goals across the sub-worlds: 0"},
         {"head": "Rebuild engine", "icon": "cube", "text": "Rebuild from play and prove a goal: 0"}]},
    {"type": "timeline", "title": "Why guessing the goal by machine cannot cross it",
     "items": [
         {"t": "Tiny corner", "text": "Exploring touches only 50-138 screens and never trips the reward"},
         {"t": "One-shot", "text": "On s5i5 it thinks a timer is the goal"},
         {"t": "Thin feedback", "text": "It only says 'wrong', never 'warmer'; a huge cold brute-force sweep (E146) won 0 new games"},
         {"t": "The wall", "text": "The stuck point is guessing the goal -- not copying, planning, or exploring"}]},
    {"type": "statement",
     "text": "A copy of the game is useless until it holds a proven path to the win. Exploring more of the game does not help."},

    {"type": "section", "title": "The landscape of approaches"},
    {"type": "figure", "title": "Which approach solves which game",
     "image": "figs/arc3_strategy_heatmap.png",
     "caption": "The goal-guessing columns are empty; only the reasoning agent lights up the hard games",
     "bullets": [
         "Directed search and map-building each solve 6 games",
         "Combining several ways of seeing reaches 10 (best of the automatic tiers)",
         "The live coding agent lights up the recipe-walls nothing else can touch"]},
    {"type": "compare", "title": "Three kinds of approach",
     "left": {"head": "Automatic ways", "icon": "compass",
              "items": ["Guess the goal: all fail -- 0 hard games, even with a perfect copy",
                        "Seeing and searching: only games you can stumble into"]},
     "right": {"head": "Reasoning agent", "icon": "gear",
               "items": ["The only way that crosses the walls"]}},
    {"type": "bigstat", "title": "The reasoning agent that writes its own copy of the game",
     "value": "15 of 25", "sub": "the live agent, on its own",
     "points": ["Claude Code: one working session per game, no trying over and over",
                "The prompt gives only the controls and the recipe -- never how to win",
                "Crosses every wall the automatic ways miss (dc22, g50t, ka59, ...)",
                "Reasons out the goal instead of searching a fixed list of guesses"]},

    {"type": "part", "title": "Results", "subtitle": "All 25 solved, a stronger model solves more, and the atlas"},
    {"type": "stats", "title": "The first time every game was solved this way",
     "items": [{"value": "25/25", "label": "games, no code read", "hi": True, "icon": "grid"},
               {"value": "183/183", "label": "levels solved", "icon": "stack"},
               {"value": "1st", "label": "perfect run", "icon": "check"}]},
    {"type": "figure", "title": "Every game solved, one by one (a stronger model solves more)",
     "image": "figs/arc3_source_matrix.png",
     "caption": "Claude Fable clears all 25 games; a stronger model clears more walls for the same budget",
     "bullets": [
         "Claude Fable 5: 25/25 games, 183/183 levels -- the first perfect run",
         "Main run Claude Opus 4.8: 16/25 (158 levels) on the exact same setup",
         "GPT-5.5: 12/25; best earlier work (baseline1): 15/25 (145 levels)",
         "All proven by re-playing the moves; none use stored answers"]},
    {"type": "timeline", "title": "The headline numbers, read carefully",
     "items": [
         {"t": "25/25", "text": "Fable with no code read, done 2026-07-04 09:05:14 UTC"},
         {"t": "Beats best", "text": "On games, levels, and how few moves it used"},
         {"t": "lf52", "text": "Clears the one level no earlier run ever solved"},
         {"t": "Runnable", "text": "Every solved game is a real world you can run and open; public games only, the private hidden set was untouched"}]},
    {"type": "figure", "title": "A stronger model clears more walls",
     "image": "figs/pres_arc3_scaling.png",
     "caption": "Same setup, same prompt, same budget -- only the model changes",
     "bullets": [
         "GPT-5.5 12 -> Opus 16 -> Fable 25 of 25 games",
         "Fable finds each solve using about 3.5x less text (23M vs 81M)"]},
    {"type": "figure", "title": "How few moves it used, per level (Fable, no code read)",
     "image": "figs/arc3_rhae.png",
     "caption": "Every game matches or beats a person; per-level score min((b/a)^2 * 100, 115)",
     "bullets": [
         "Fable used far fewer moves than a person: score 100.0 vs the earlier best's 58 (~72% better)",
         "174 of 183 levels beat the person; 168 hit the top score of 115",
         "Moves per level are usually about a third of a person's",
         "Scored by the game's own tool -- we did not rebuild the measure"]},
    {"type": "figure", "title": "An honest baseline: levels reached vs random play",
     "image": "figs/arc3_above_random.png",
     "caption": "Random play reaches the first level of 11/25, but finishes 0 games all the way",
     "bullets": [
         "With unlimited free restarts offline, about half the 'reached one level' count is free",
         "One 'solve' (lp85, one click over and over) is no better than random",
         "What really counts: 14 games random never even reaches (the walls)",
         "So we report 16/25 as clearly better than random"]},

    {"type": "section", "title": "The atlas: every solve is a world"},
    {"type": "figure", "title": "25 games, 25 working worlds you can open",
     "image": "figs/arc3_maps_gallery.png",
     "caption": "A winning screen from Fable's from-scratch solve of every game",
     "bullets": [
         "Each solve: turn the picture into facts -> a rules program -> a goal check",
         "Saves as a one-page atlas card, and runs at openworld serve /view",
         "25 clearly different worlds: moving, clicking, box-pushing, mirrors, building"]},
    {"type": "figure", "title": "Example solve: ka59 (7/7)",
     "image": "figs/arc3_replay_ka59.png",
     "caption": "The world-model card (top) plus the level-by-level replay (bottom)",
     "bullets": [
         "The card's map is the path through the levels, with each step's button on it",
         "The replay: real screenshots at each level clear, re-run against the game"]},
    {"type": "figure", "title": "Example solve: dc22 (6/6) -- a recipe wall",
     "image": "figs/arc3_replay_dc22.png",
     "caption": "Mixes moving and clicking; only the reasoning agent crosses it",
     "bullets": [
         "Random play never even reaches level 1 here",
         "A key-and-box routine slides a movable structure into place"]},
    {"type": "figure", "title": "Example solve: g50t (7/7) -- ghost-switch",
     "image": "figs/arc3_replay_g50t.png",
     "caption": "A big 94-spot map never proves a win on its own -- reasoning is what does it",
     "bullets": [
         "Hold-down plates, toggle buttons, warp rings, a pinball ghost that copies you",
         "The value is the proven winning chain, not how big the map is"]},
    {"type": "figure", "title": "The last wall: lf52 (10/10)",
     "image": "figs/arc3_replay_lf52.png",
     "caption": "The one level no run had ever solved -- a proven 914-move path",
     "bullets": [
         "Cracked with a keep-your-notes deep-wall routine",
         "Build a proven copy of the level, then search it offline at full scale",
         "Solving it completed the perfect 25/25 sweep"]},
    {"type": "figure", "title": "Example solve: su15 (9/9) -- merge and deliver",
     "image": "figs/arc3_replay_su15.png",
     "caption": "Click to gather; matching tiers merge and grow; a 141-click solution",
     "bullets": [
         "The clickable targets were figured out from the pixels alone",
         "Runs as a real, openable OpenWorld world"]},

    {"type": "section", "title": "How the models actually solve (the play-by-play)"},
    {"type": "figure", "title": "The shape of a solve",
     "image": "figs/e150_cardiogram.png",
     "caption": "Read/Write-heavy start (building) -> Bash-heavy middle (searching) -> Edit fixes",
     "bullets": [
         "Levels get cleared in sudden jumps, not steady progress",
         "Build first, then search -- the same shape in every solve"]},
    {"type": "figure", "title": "The words each game made the agent invent",
     "image": "figs/e150_concepts.png",
     "caption": "The names the agent chose in its code recover each game's mechanics, with no help",
     "bullets": [
         "ka59 -> box/push/ring (box-pushing); ft09 -> blk/slots (stencil)",
         "The ideas the agent had to invent tell you what kind of puzzle it was"]},
    {"type": "figure", "title": "The signature of each solution",
     "image": "figs/e150_signatures.png",
     "caption": "Each winning path as a strip of moves: clicks, moving, or a mix",
     "bullets": [
         "Ochre = click (ACTION6); blue = moving (1-5,7)",
         "A picture-map of each solution's shape and length (lf52 is longest)"]},
    {"type": "figure", "title": "Where the agent clicked",
     "image": "figs/e150_clicks.png",
     "caption": "How thick the winning clicks land on the 64x64 board -- no hidden list of targets",
     "bullets": [
         "The clickable spots the agent figured out from the pixels alone",
         "opus looks harder at the picture; Fable leans on memory plus checking"]},

    {"type": "part", "title": "Reflection", "subtitle": "Honest limits and what comes next"},
    {"type": "stats", "title": "It is the best of many tries; a single try is not reliable",
     "items": [{"value": "~823", "label": "sessions across 25 games (about 33 per game)", "icon": "bars"},
               {"value": "~6%", "label": "a full win on ~6% of tries overall, as low as ~2% on bp35/lf52", "icon": "gauge", "hi": True},
               {"value": ">1 seed", "label": "a clean fixed-prompt, many-seed test is a clear next step", "icon": "route"}]},
    {"type": "quadrant", "title": "We cannot yet measure if the model saw these games in training",
     "cells": [
         {"head": "Code never read", "icon": "shield", "text": "We check that no run reads the game's code -- measured every run"},
         {"head": "Memory unknown", "icon": "scan", "text": "But we cannot rule out a public game already sitting in the model's memory"},
         {"head": "Applies to all", "icon": "bars", "text": "This applies to every top-model result, the earlier best included"},
         {"head": "0/25 by name", "icon": "lock", "text": "Fable knew 0/25 games from the name alone (a quick check, not proof)"}]},
    {"type": "contrast", "title": "Offline, unlimited restarts, one run",
     "before": {"head": "What it is", "text": "All solves are offline, with unlimited restarts and perfect replay -- a fresh fair-budget result"},
     "after": {"head": "What it is not", "text": "Not the live leaderboard, which docks you for extra moves; a repeat or a live run might change it, and the cost is a rough guess -- the perfect run was not the cheap one"}},

    {"type": "section", "title": "Conclusion"},
    {"type": "bigstat", "title": "What we showed",
     "value": "25/25", "sub": "first perfect ARC-AGI-3 run, no code ever read (Fable)",
     "points": ["Copying the game is not the wall -- the rules can be written out as code",
                "The win is a recipe of steps in order; one-screen scoring wins 0",
                "Only a reasoning agent that writes its own copy crosses it; a stronger model carries it from 16/25 to every game"]},
    {"type": "cards", "title": "The takeaway for builders",
     "cards": [
         {"head": "Win = a recipe", "icon": "route", "text": "In these games a win is a recipe of steps in order, not one good screen"},
         {"head": "Scoring fails", "icon": "target", "text": "Any one-screen score fails, even with a perfect copy -- aim at finding the recipe, not scoring screens"},
         {"head": "Runnable worlds", "icon": "cube", "text": "Every solver is an open, replay-proven, runnable world"},
         {"head": "What's next", "icon": "compass", "text": "Live-run efficiency, many-seed spread, a training-memory-controlled test"}]},
    {"type": "statement",
     "text": "The recipe of steps is the wall. Reasoning is the ladder. Every solve downloads, re-runs, and opens as a world."},
]
