TITLE = "World-Time Computing"
SUBTITLE = "A Next Frontier for Simulated Learning — turning compute into unlimited, exactly-labeled experience"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "section", "title": "Motivation: Manufacturing Experience"},
    {"type": "bullets", "title": "The problem: experience is scarce",
     "bullets": [
         "LLMs generalize only after many real, labeled examples",
         "In most domains that experience is scarce and costly",
         "We study a way to manufacture it cheaply",
         "Idea: when dynamics can be written as code, simulate the experience"]},
    {"type": "bullets", "title": "Two species of world model",
     "bullets": [
         "Perceptual/generative: learned nets, latents/pixels/video (Dreamer, Genie, Sora)",
         "Data-hungry, compounding error, opaque weights",
         "Code World Models (CWMs): transition is a readable program over symbolic state",
         "Synthesized by an LLM, verified before use, exact rollouts, zero training data"]},
    {"type": "statement",
     "text": "Where spatial-intelligence systems learn what cannot be told, OpenWorld writes down what can be told -- and verifies it."},
    {"type": "bullets", "title": "Two conditions make it work",
     "bullets": [
         "Worlds must not lie: dynamics are verified code, not learned approximations",
         "Accepted only if it parses, runs sandboxed, preserves invariants, survives a critic",
         "Need many worlds -- each must be cheap to build",
         "OpenWorld makes authoring a verified world a minutes-scale activity"]},
    {"type": "bullets", "title": "Contributions",
     "bullets": [
         "World-time compute on real domains, with cross-world transfer",
         "Why it must be verified code: exact rollouts, no compounding error",
         "OpenWorld substrate + full reproducibility (79 experiments, seed-fixed)"]},

    {"type": "section", "title": "Problem Setting"},
    {"type": "bullets", "title": "Symbolic-state worlds",
     "bullets": [
         "State is JSON-serializable; actions discrete; dynamics declarable as rules",
         "Covers triage, negotiation, portfolios, sprints, program repair",
         "Not pixel-native domains -- that is the scope boundary",
         "The adversary is model error: hallucinated transitions, silently wrong code"]},
    {"type": "bullets", "title": "A world model, formally",
     "bullets": [
         "W = (states, actions, s0, transition tau, weighted objectives, invariants)",
         "Practitioner declares everything but tau (schema, actions, rules, dials)",
         "Framework produces tau by synthesis under verification, not learning",
         "Certifies invariant-consistency, not equality to true dynamics"]},
    {"type": "bullets", "title": "The compounding-error argument",
     "bullets": [
         "Fixed program: right once means exact at every rollout depth, bit-for-bit",
         "Per-step predicted transition stays exact for only ~(1-eps)^t of a t-step rollout",
         "Error budget paid once at synthesis time, where it is auditable",
         "Same World serves as both ground-truth environment and planning model"]},

    {"type": "section", "title": "Method & Experimental Setup"},
    {"type": "bullets", "title": "Worlds and models",
     "bullets": [
         "Three oracle worlds: sprint, orchard, triage (hand-written ground truth)",
         "Coding world: 20 buggy-function repair tasks, transition = test execution",
         "Local Ollama models: qwen2.5 1.5B/3B/7B, plus Llama-3.1-8B, Gemma2-9B",
         "Fine-tuning runs: single cloud A100, 4-bit QLoRA"]},
    {"type": "bullets", "title": "Baselines and metrics",
     "bullets": [
         "LLMTransition: same backbone predicting each next state (learned-style proxy)",
         "Trained MLP + 1-NN on K = 100 / 1k / 10k random transitions",
         "Exact-state match, first-divergence step, final L1 error; pass@k for repair",
         "95% Wilson CIs; every number regenerates from one script"]},

    {"type": "section", "title": "The Central Result"},
    {"type": "figure", "title": "Verified code eliminates compounding error",
     "image": "figs/hero.png",
     "caption": "A: code exact at every depth vs LLM diverging by step ~2.3. B: world-time compute payoff.",
     "bullets": [
         "Code (blue) matches oracle exactly across a 20-step rollout",
         "Per-step LLM (orange) first diverges ~step 2.3, never completes exactly",
         "B: fine-tuning on 60 verified worlds lifts held-out accuracy",
         "Largest gain for smallest models: +29 pts at 0.5B, +3 at 32B"]},
    {"type": "bullets", "title": "Head-to-head dynamics fidelity (E1/E4/E11)",
     "bullets": [
         "Verified code exact on 24/24 twenty-step rollouts (CI [0.86, 1.00])",
         "Per-step LLM: 0/24 exact rollouts (CI [0.00, 0.14])",
         "Code rolls out at ~15,000 steps/s vs LLM's 0.32 steps/s",
         "OOD probes: code 100% exact from zero transitions"]},
    {"type": "statement",
     "text": "The robust claim is the exact-match contrast, not the mean divergence step -- compounding depends on per-world error rate."},

    {"type": "section", "title": "World-Time Compute: Traversing Worlds to Generalize"},
    {"type": "bullets", "title": "What world-time compute is",
     "bullets": [
         "A verified world is also a generator of unlimited exactly-labeled experience",
         "Traverse many worlds of a domain, distill the shared skill",
         "Training-time analogue of test-time compute",
         "Tested on a family of 60+20 diagnosis-specialty POMDP worlds (E74)"]},
    {"type": "figure", "title": "Anatomy of one diagnosis world (E74)",
     "image": "figs/diagnosis_world.png",
     "caption": "Hidden disease -> emitted symptoms; agent inverts observation to name the disease.",
     "bullets": [
         "Each specialty is a small hidden-state simulator with a known label",
         "Agent treats its own verified world as ground truth",
         "Train on many specialties, test on held-out ones",
         "Forces the general skill, not memorization"]},
    {"type": "bullets", "title": "Two findings (E74)",
     "bullets": [
         "Generalization, not memorization: lift at every model size on unseen worlds",
         "0.5B: 37% -> 66%; 32B: 78% -> 81% toward the 86% rules-given oracle",
         "A small-model multiplier: +29 pts at 0.5B, shrinking to +3 at 32B",
         "Heterogeneous worlds sharing no skill (E71/E73) give no transfer"]},

    {"type": "section", "title": "Scaling the Lever"},
    {"type": "figure", "title": "World-count scaling (E76)",
     "image": "figs/world_count.png",
     "caption": "Held-out accuracy vs number of train worlds; still climbing at 512 worlds.",
     "bullets": [
         "Too few worlds hurt (below 48% base) -- overfits a narrow slice",
         "Gain then rises monotonically, no plateau",
         "Still climbing at 512 worlds: 59% (+10 pts), heading toward 69% oracle",
         "A genuine scaling lever in the number of worlds"]},
    {"type": "figure", "title": "Exact labels are the lever (E78b)",
     "image": "figs/noise_ablation.png",
     "caption": "Corrupt a fraction p of training labels; accuracy falls monotonically.",
     "bullets": [
         "256 worlds fixed; only training labels corrupted at rate p",
         "Verified (p=0): 35%; fully wrong (p=1): 19%, at/below floor",
         "Label exactness -- not task variety -- drives the effect",
         "This is what separates world-time compute from domain randomization"]},
    {"type": "bullets", "title": "A coding-world family (E77)",
     "bullets": [
         "164 function-implementation worlds, each verified by its pytest oracle",
         "In-domain: 7B pass@5 lifts 84% -> 95% at every size",
         "HumanEval (OOD): hurts greedy pass@1 (78% -> 70%)",
         "But transfers positively at pass@5 (87% -> 91%) from only 164 worlds"]},

    {"type": "section", "title": "Real Data: World-Time Compute on ARC-AGI"},
    {"type": "figure", "title": "How WTC fine-tunes on a verified world (E80)",
     "image": "figs/arc_method.png",
     "caption": "ARC task -> augmented exactly-labeled rows -> QLoRA on frozen 4-bit Qwen2.5-7B.",
     "bullets": [
         "Each ARC task is a world with a latent rule shown by demonstrations",
         "Rule-preserving augmentation (dihedral x color) -> unlimited labeled rows",
         "Two strict holdouts: cross-task ladder and per-world test-time training",
         "Corrupted-label arm is the discriminator"]},
    {"type": "figure", "title": "World-time compute on real ARC-AGI (E80)",
     "image": "figs/arc.png",
     "caption": "Per-world TTT lifts exact-match; cross-task transfer stays weak.",
     "bullets": [
         "Zero-shot 2% -> light 8% -> heavy 10% (+8 pts) with more compute",
         "Corrupted demos fall to 2%, at the zero-shot floor",
         "Lift requires verified labels -- the model learns each real rule",
         "Cross-task transfer weak (3% -> 5%): every ARC rule is novel"]},
    {"type": "figure", "title": "Across real domains and modalities (E80)",
     "image": "figs/worldtime_domains.png",
     "caption": "Scales and collapses on symbolic domains; Bongard vision stays at chance.",
     "bullets": [
         "List Functions: 35% -> 66% -> 69% (heavy); corrupt 3%",
         "CLRS algorithms: 9% -> 13% -> 17%; corrupt 4%",
         "Effect largest for shallow rules, smallest for long algorithm traces",
         "Bongard-RWR (vision): flat at chance (46/48/52%) -- the perceptual boundary"]},

    {"type": "section", "title": "Cross-World Transfer on a Real Domain"},
    {"type": "figure", "title": "Cross-world transfer, List Functions (E84)",
     "image": "figs/crossworld.png",
     "caption": "One adapter on 128 disjoint worlds generalizes to 60 held-out worlds.",
     "bullets": [
         "Cross-world 40% (CI [35,45]) on worlds never seen",
         "Corrupted-label control only 6% -- a +34-pt exactness-gated lift",
         "Gap is rule-induction transferring across worlds, not formatting",
         "The novel axis, demonstrated on data we did not generate"]},
    {"type": "figure", "title": "Cross-world transfer scales with #worlds (E84)",
     "image": "figs/crossworld_ladder.png",
     "caption": "Held-out accuracy 29% -> 49% rising then plateauing near 64 worlds.",
     "bullets": [
         "Rises from 29% at 16 worlds to a 49% peak by 64 worlds",
         "Corrupted-label control stays flat",
         "A rising-then-plateauing scaling curve on real data",
         "More verified worlds -> more transfer"]},
    {"type": "bullets", "title": "A descriptive regularity (E80)",
     "bullets": [
         "Saturating learning curve: acc(c) = base + (C-base)(1 - e^{-c/kappa})",
         "Asymptote tracks identifiability x realizability x headroom",
         "Light-dose probe predicts heavy asymptote (Spearman 0.73-0.98)",
         "Holds for a non-neural program synthesizer too (learner-invariance)",
         "N90 worlds: List Functions 3, ARC 9, CLRS 15 -- harder needs more"]},

    {"type": "section", "title": "Boundaries & Negatives"},
    {"type": "figure", "title": "Frame-invariance is a negative (E81)",
     "image": "figs/frame_invariance.png",
     "caption": "Cross-language-frame TTT does not beat zero-shot on either base.",
     "bullets": [
         "One problem in 5 languages; train on other frames, test held-out language",
         "Strong coder flat (28% -> 30%); weak base drops (29% -> 27%)",
         "Only weak exactness ordering survives (matched > corrupt)",
         "A held-out language behaves as its own skill -- an honest boundary"]},
    {"type": "figure", "title": "The hybrid loop (E82)",
     "image": "figs/hybrid_loop.png",
     "caption": "Verified world as generator + verify-and-retry backstop on HumanEval-X.",
     "bullets": [
         "Amortization helps strong base (80% -> 85%) but hurts weak one (57% -> 50%)",
         "Hybrid loop lifts both above base: Qwen 90% (+10), Llama 65% (+8)",
         "Weak base leans on the verifier more (2.65 vs 1.45 calls/problem)",
         "Exactness used as an oracle is sufficient -- the robust default route"]},

    {"type": "section", "title": "Against Trained & Perceptual Dynamics"},
    {"type": "figure", "title": "Trained baselines vs zero-transition program (E12)",
     "image": "figs/learned.png",
     "caption": "MLP/1-NN trained on K transitions; none transfers out of distribution.",
     "bullets": [
         "At K=10,000 the MLP reaches only 50% in-dist, 0% at 10x OOD",
         "Synthesized program: 100% on both from zero transitions",
         "1-NN memorizes rollouts (8/8) yet scores 30% on branch probes",
         "OOD + branch-covering probes, not rollout agreement, measure quality"]},
    {"type": "figure", "title": "Induction does not scale with capability (E38)",
     "image": "figs/induction_scale.png",
     "caption": "Trace-induction probe accuracy flat across three generator families.",
     "bullets": [
         "From traces alone (no rule text): 0.43 (7B), 0.33 (30B coder), 0.43 (gpt-oss)",
         "None approaches the rule-text anchor of 1.00",
         "Every model exactly scale-invariant (in-dist = 10x OOD)",
         "An identifiability limit of the data, not a capability limit"]},
    {"type": "figure", "title": "Acting closes the gap scale cannot (E43)",
     "image": "figs/active_induction.png",
     "caption": "Active version-space elimination beats passive observation.",
     "bullets": [
         "Active policy identifies the exact rule in 11.2 transitions vs 14.7 passive",
         "Passive never resolves 2/5 high-k rules within budget",
         "Active (knowing nothing) matches clairvoyant reference (11.2 vs 11.6)",
         "When traces underdetermine dynamics, choose the transitions"]},
    {"type": "figure", "title": "The complexity cliff (E20)",
     "image": "figs/complexity.png",
     "caption": "Synthesis accuracy vs number of declared interacting rules.",
     "bullets": [
         "R=4: 1.00; R=8: 0.53; R=12: 0.25; R=16: 0.15",
         "Monolithic 7B synthesis unreliable past ~8 coupled rules",
         "The paradigm's present boundary at this model scale",
         "Motivates compositional synthesis -- one expert per rule"]},

    {"type": "section", "title": "From Fidelity to Decisions"},
    {"type": "bullets", "title": "Planning through a verified world (E22)",
     "bullets": [
         "Model-predictive depth-3 lookahead, best action executed in ground truth",
         "Planning through verified program scores 7.5 -- identical to the oracle",
         "Reactive heuristic 5.0; random 3.8; whole episode planned in 0.03 s",
         "Planning through the LLM engine scores 0.0 -- worse than no model"]},
    {"type": "bullets", "title": "Crossing species: bake-off (E63/E65/E67)",
     "bullets": [
         "6 runnable models x 2 symbolic domains: verified code exact and optimal",
         "Every learned model collapses to 0% exact at 10x OOD",
         "MiniGrid DoorKey: OpenWorld solves zero-shot in an 11-step plan",
         "DreamerV3 needs ~9,640 interactions to first solve; V-JEPA-2 cannot control"]},

    {"type": "section", "title": "Discussion & Limitations"},
    {"type": "bullets", "title": "Is world-time compute just fine-tuning?",
     "bullets": [
         "Mechanically yes -- LoRA-SFT; the claim is about the data source",
         "A correct world model turns compute into unlimited correct training data",
         "Two things earn the name: verified-label dependence and cross-world transfer",
         "Where neither holds, it is fairly just expensive fine-tuning -- and we say so"]},
    {"type": "bullets", "title": "The trajectory unit, measured (E85)",
     "bullets": [
         "Training unit is a transition (s,a,s'), not a final answer",
         "At the trained horizon: trajectory 70% vs answer 58% (+12 pts)",
         "Rolled out longer than trained, answer unit catches up (75% vs 68%)",
         "Composing per-step predictions reintroduces compounding on the learned side"]},
    {"type": "bullets", "title": "When does it pay off? Few-step reasoning",
     "bullets": [
         "Wins where a task is few steps over state that can be told symbolically",
         "Shallow rule induction, small grid transforms, short-horizon planning",
         "Degrades as reasoning lengthens (CLRS traces, >8 composed rules)",
         "Cedes long-horizon, perception-heavy regimes to learned models"]},
    {"type": "bullets", "title": "Three routes to use a verified world model",
     "bullets": [
         "Route 1 -- Tool: serve, plan, verify; exact, auditable, no training",
         "Route 2 -- Per-world TTT: distill one world's trajectories (approx.)",
         "Route 3 -- World-time compute: traverse a family, generalize to new worlds",
         "Hybrid: generate exact data, internalize it, exact backstop on demand"]},
    {"type": "bullets", "title": "Limitations (selected)",
     "bullets": [
         "Scope: symbolic-state worlds; pixel-native stays learned models' territory",
         "Complexity cliff past ~8 rules; headline worlds sit below it",
         "Many stochastic headline numbers are single-seed point estimates",
         "No family-wise correction over 79 experiments -- borderline p-values exploratory"]},

    {"type": "section", "title": "Conclusion"},
    {"type": "statement",
     "text": "Make the model a program, verify the program, and keep the values dialable -- an orthogonal path to scaling parameters until hallucination is suppressed."},
    {"type": "bullets", "title": "Takeaways",
     "bullets": [
         "Verified code world models are bit-exact where learned dynamics compound error",
         "Plan as well as ground truth; hallucinated planning is worse than none",
         "Traversing many verified worlds lifts generalization to held-out worlds",
         "Next: compositional synthesis, benchmark-scale coding, perception-to-symbol pipelines"]},
]
