TITLE = "World Models: An Overview and Applications"
SUBTITLE = "Small programs we check are right that copy how a world works, so we can build them, check them, join them, walk through them, and share them"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The whole talk in one picture"},
    {"type": "part", "title": "The basics", "subtitle": "What is one of these little world programs?"},
    {"type": "anim", "diagram": "worldmodel", "title": "The building block of computing with worlds",
     "still": "figs/prototyping_pipeline.png"},
    {"type": "bullets", "title": "Two kinds of these world programs",
     "bullets": [
         "Picture-guessers: big neural nets that dream up pixels (Dreamer, Genie, Sora)",
         "Strong, but they need tons of data, their small mistakes pile up, and you cannot see inside",
         "Code worlds: the rule for what happens next is plain code you can read",
         "An AI writes the code, we check it is right before using it, and it is exact and easy to inspect",
         "The two kinds help each other; they are not rivals"]},
    {"type": "bullets", "title": "Why use code we check is right",
     "bullets": [
         "It runs exactly, fast, and you can audit it, and an agent can call it like a tool",
         "Same input, same answer: no piled-up mistakes; guessed rules rot as (1-e)^t",
         "Plain code plays out a world about 47,000x faster than asking an LLM each step",
         "At every step the thing you hold is code you can read and diff"]},
    {"type": "statement",
     "text": "Turn the model into code, check the code is right, and keep the values easy to turn up or down."},
    {"type": "stats", "title": "Three results, one shared idea",
     "items": [{"value": "100", "label": "checked worlds built in minutes", "icon": "nested"},
               {"value": "+29 pts", "label": "gain from making many practice worlds", "icon": "bars"},
               {"value": "25/25", "label": "ARC-AGI-3, without reading the game's code", "hi": True, "icon": "grid"}]},

    {"type": "part", "title": "The toolkit", "subtitle": "OpenWorld"},
    {"type": "figure", "title": "One agent writes worlds that are checked and ready to share",
     "image": "figs/world_computer.png",
     "caption": "Measured on cost, speed, and quality; code we check is right ran about 47,000x faster than an LLM",
     "bullets": [
         "Built 100 worlds, about 2.8 minutes each",
         "14,997 steps a second, versus 0.32 when asking an LLM each step",
         "100% pass the structure check; 99% behave correctly when run"]},
    {"type": "figure", "title": "A code world, start to finish",
     "image": "figs/prototyping_pipeline.png",
     "caption": "See -> world -> report/act, all built from a real spec so the labels cannot drift",
     "bullets": [
         "Sensors turn any kind of input into the world as plain facts",
         "Checked rules step forward inside big worlds made of small checked pieces",
         "Goals (with turnable dials) give a score; the world sends back reports and tool-calls"]},
    {"type": "bullets", "title": "The plan, write, check relay",
     "bullets": [
         "You describe a world; a writer produces the rule: next = f(now, action)",
         "Check 1: it parses; Check 2: it runs safely and keeps the promises; Check 3: a critic reads it",
         "Accepted code is plain, editable code -- failures feed back into the next try",
         "Joining keeps the checks: checked pieces make a checked whole"]},

    {"type": "part", "title": "Three results", "subtitle": "Building worlds, learning from many worlds, solving ARC-AGI-3"},
    {"type": "bullets", "title": "Building a world takes minutes (E68)",
     "bullets": [
         "100 worlds across 6 regulated fields, each from a one-line request",
         "About 2.8 minutes each; all pass the structure check; 99% run correctly",
         "Hand-building a matching simulator would take days to weeks"]},
    {"type": "figure", "title": "How exact and how fast (E04, E11)",
     "image": "figs/pres_speed.png",
     "caption": "Exact on all 24 of 24 twenty-step runs and 10x harder probes -- no piled-up mistakes",
     "bullets": ["About 47,000x faster to play out than asking an LLM each step"]},
    {"type": "anim", "diagram": "cliff", "title": "Small checked pieces beat the difficulty wall",
     "still": "figs/composition_cliff.png"},
    {"type": "figure", "title": "Turnable values: the moral dial (E8)",
     "image": "figs/pareto.png",
     "caption": "A well-being vs fairness trade-off swept by one dial; the values are stated, weighted things",
     "bullets": [
         "Every dial setting is a best-possible trade; move it without any retraining",
         "Hard vetoes and a voting council are separate parts, not just weights",
         "Values are written down openly and steered by simple procedure"]},

    {"type": "section", "title": "Result II — Learning from many practice worlds"},
    {"type": "anim", "diagram": "worldtime", "title": "Making practice experience on purpose",
     "still": "figs/crossworld_ladder.png"},
    {"type": "anim", "diagram": "compounding", "title": "Code we check is right stops mistakes from piling up",
     "still": "figs/hero.png"},
    {"type": "figure", "title": "Skill carries to new worlds as you add worlds (E84)",
     "image": "figs/crossworld_ladder.png",
     "caption": "Held-out List Functions score climbs 29% -> 49% as the number of checked worlds grows",
     "bullets": [
         "One learner trained on 128 separate worlds does well on 60 it never saw",
         "A version with scrambled labels stays flat -- exact labels are what matter",
         "A real growth curve, on data we did not make up"]},
    {"type": "figure", "title": "Across real subjects (E80)",
     "image": "figs/worldtime_domains.png",
     "caption": "Grows on rule-based subjects (List Functions, CLRS, ARC); flat on Bongard pictures",
     "bullets": [
         "List Functions 35% -> 69%; ARC, practicing each world, +8 pts",
         "Biggest help for short simple rules, smallest for long ones",
         "Bongard picture task stays at guessing level -- the seeing barrier"]},

    {"type": "section", "title": "Result III — Solving ARC-AGI-3"},
    {"type": "figure", "title": "An agent that writes its own world program without reading the game's code",
     "image": "figs/arc3_architecture.png",
     "caption": "See -> explore -> write code we check is right -> figure out the goal -> plan -> replay to verify",
     "bullets": [
         "Never reads the game's code; learns the rules by playing",
         "Every win becomes a shareable OpenWorld world",
         "Copying the world is exact -- the hard part is figuring out the goal"]},
    {"type": "figure", "title": "The hard part: the win is a recipe of steps, not one screen",
     "image": "figs/arc3_goal_as_procedure.png",
     "caption": "A win is an ordered recipe A->B->C, which no single-screen score can judge",
     "bullets": [
         "Four careful ways to guess the goal solve 0 -- even with a perfect world copy",
         "Scoring one screen or blind searching cannot rank an ordered recipe",
         "Only an agent that reasons out the win gets past the walls"]},
    {"type": "figure", "title": "The first perfect result without reading the code (bigger model)",
     "image": "figs/pres_arc3_scaling.png",
     "caption": "Claude Fable clears all 25 games; a stronger model breaks more walls for the same budget",
     "bullets": [
         "Claude Fable 5: 25 of 25 games, 183 of 183 levels -- first perfect run",
         "Opus 4.8: 16/25; GPT-5.5: 12/25; best earlier baseline1: 15/25",
         "Gets smarter and cheaper: Fable used about 3.5x fewer tokens"]},
    {"type": "figure", "title": "The atlas: 25 games, 25 shareable worlds",
     "image": "figs/arc3_maps_gallery.png",
     "caption": "Every win found without reading the code turns into a runnable OpenWorld world",
     "bullets": [
         "hidden-status-bar sensor -> code rule from what was learned -> code goal",
         "Runs at openworld serve /view; draws itself as an atlas card",
         "25 clearly different worlds, all discovered by playing"]},

    {"type": "part", "title": "Where it is useful", "subtitle": "Physics, economies, brains, signals"},
    {"type": "figure", "title": "Einstein's relativity as a checked world program (E47)",
     "image": "figs/relativity.png",
     "caption": "GPS fix of +38.5 us/day and the Hafele-Keating clock shifts, from stated physics",
     "bullets": [
         "Time slowing is exact; a slow-speed guessed fit goes wild as speed nears light",
         "Stated, checked law where guessed video models miss the physics"]},
    {"type": "figure", "title": "An economy that emerges from joined rules (E44)",
     "image": "figs/emergent_economy.png",
     "caption": "6 people; inequality 0.22 -> 0.001 with sharing; the books balance exactly every tick",
     "bullets": [
         "Big-picture numbers are just sums built from small checked parts",
         "Each effect isolated by flipping one checked rule on or off"]},
    {"type": "figure", "title": "A brain as a world made of worlds (E58)",
     "image": "figs/brain_card.png",
     "caption": "Awake mind + hidden mind + surroundings, linked by recall, store, and act bridges",
     "bullets": [
         "Short-term memory + searchable long-term memory + the world outside",
         "The whole brain saves to a spec and rebuilds with nothing lost"]},
    {"type": "figure", "title": "See it, then forecast an outbreak (E40)",
     "image": "figs/perception.png",
     "caption": "The seen world is exact both on and off familiar data; the neural-net fit falls apart at 10x scale",
     "bullets": [
         "Text plus a photo read into healthy/sick/recovered counts, then rolled 14 days ahead",
         "The rules add zero error -- the forecast is as good as the reading was"]},
    {"type": "figure", "title": "A same-day stock trading world (E50)",
     "image": "figs/trading.png",
     "caption": "Real prices, tested forward in time, after costs -- about rigor and audit, not easy money",
     "bullets": [
         "It finds a known fake +40 bps edge, so a weak real result is trustworthy",
         "Honest and fragile to costs: score 0.59 < the market's 0.77"]},
    {"type": "figure", "title": "Portable, auditable world specs and cards (E57)",
     "image": "figs/world_card.png",
     "caption": "One self-contained picture drawn from a world's spec; rebuilds with nothing lost",
     "bullets": [
         "Facts, rules, dynamics, seeing/reporting, goals -- all captured",
         "Exports to Mermaid and React Flow; a tradeable unit for worlds"]},

    {"type": "part", "title": "The big picture", "subtitle": "The story so far, and what comes next"},
    {"type": "cards", "title": "Three ways to use a checked world program",
     "cards": [
         {"head": "As a tool", "icon": "gear", "text": "Run it, plan, verify — no training"},
         {"head": "Practice one world", "icon": "flask", "text": "Learn from one world's playthroughs"},
         {"head": "Practice many worlds", "icon": "nested", "text": "Walk a whole family; carry the skill over"},
         {"head": "Both together", "icon": "atom", "text": "Exact data plus a checking safety net"}]},
    {"type": "bullets", "title": "The lessons that carry over",
     "bullets": [
         "Code we check is right is exact where guessed rules pile up mistakes",
         "Small checked pieces beat the difficulty wall -- and we measured where it is",
         "Wins in games are ordered recipes; aim at finding the recipe",
         "Walking many checked worlds makes skill carry to worlds never seen"]},
    {"type": "cards", "title": "Limits and honesty",
     "cards": [
         {"head": "What it covers", "icon": "grid", "text": "Worlds of facts, not raw pixels"},
         {"head": "How complex", "icon": "lock", "text": "Joins hold to about 8 tangled rules"},
         {"head": "Honesty", "icon": "scan", "text": "ARC-3 is best of many tries; leakage not measured"},
         {"head": "Next", "icon": "route", "text": "Join more pieces · turn sights into facts · live testing"}]},
    {"type": "statement",
     "text": "Build the world as code we check is right. Walk it for practice. Reason out the goal. Share it with anyone."},
]
