TITLE = "An Introduction to World Computing"
SUBTITLE = "Build, verify, compose, and serve simulated worlds with verifiable code dynamics"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The talk in one map"},
    {"type": "part", "title": "Motivation", "subtitle": "From computing to world computing"},
    {"type": "stats", "title": "Prototyping a verified world",
     "items": [{"value": "100", "label": "world models, 6 sectors", "icon": "nested"},
               {"value": "2.8 min", "label": "median build time", "hi": True, "icon": "flask"},
               {"value": "47,000×", "label": "faster than an LLM", "icon": "bolt"}]},
    {"type": "bullets", "title": "What is a world computer?",
     "bullets": [
         "Hardware + software that instantiates, verifies, composes, runs simulated worlds",
         "Dynamics are executable, checkable code -- not learned weights",
         "Classical computing made computation a cheap, inspectable commodity",
         "World computing aims to do the same for worlds",
         "Unit of work: a world model -- predicts next state given state and action"]},
    {"type": "compare", "title": "Two species of world models",
     "left": {"head": "Perceptual / generative", "icon": "atom",
              "items": ["Pixels / latents (Dreamer, Sora)", "Data-hungry", "Compounding error", "Opaque weights"]},
     "right": {"head": "Code world models", "icon": "code",
               "items": ["A readable program over state", "Synthesized, then verified", "Exact at every depth", "Auditable source"]}},
    {"type": "bullets", "title": "Why verified code",
     "bullets": [
         "Value is not novel dynamics -- the model can often recite the rule",
         "It is exact, fast, auditable execution an agent can call as a tool",
         "Deterministic: no compounding error; learned dynamics decay as (1-e)^t",
         "Plain code rolls out orders of magnitude faster than a per-step LLM",
         "PyTorch didn't give new models -- it made them fast to prototype"]},
    {"type": "bullets", "title": "World, action, agent, simulation",
     "bullets": [
         "World = symbolic state + discrete actions + verified transition",
         "Agent = a separate policy; a user of a world, not part of it",
         "Simulation = agents in a world producing scored trajectories",
         "A verified model relocates the sim-to-real gap into spec + perception",
         "So one World serves as both ground-truth environment and planning model"]},
    {"type": "figure", "title": "The world computer, benchmarked on cost, latency, performance",
     "image": "figs/world_computer.png",
     "caption": "One agent authors validated, servable worlds; verified code rolls out ~47,000x faster than an LLM",
     "bullets": [
         "A: 100 worlds authored at a median of 2.8 min each (p90 3.9)",
         "B: verified code at 14,997 steps/s vs 0.32 for a per-step LLM proxy",
         "C: 100% validate structurally, 99% pass a behavioral execution audit"]},
    {"type": "bullets", "title": "Contributions",
     "bullets": [
         "World computing + a verification-preserving composition algebra",
         "OpenWorld: declared worlds, verified code, dial-steerable objectives",
         "Prototyping: 100 worlds, 6 sectors, minutes each, on consumer hardware",
         "Runtime: native-speed, exact, inspectable rollouts",
         "Evaluation, trust gates, and portable, auditable specs"]},

    {"type": "part", "title": "The system", "subtitle": "OpenWorld: components, the relay, composition"},
    {"type": "bullets", "title": "Six unit-testable components",
     "bullets": [
         "World: state ontology, actions, rules, pluggable transition engine",
         "Three engines: CodeTransition, LLMTransition (baseline), FunctionTransition (oracle)",
         "Agent: LLM planner or deterministic policy",
         "Objective + Dial: open, tunable value specification",
         "Simulation, Tuner, Judge -- all over a local Ollama backbone, zero runtime deps"]},
    {"type": "flow", "title": "The plan--generate--verify relay",
     "steps": ["Declare", "Generate", "Gate 1: parse", "Gate 2: sandbox", "Gate 3: critic", "Accept"],
     "icons": ["grid", "code", "check", "shield", "gear", "check"]},
    {"type": "figure", "title": "A code world model, end to end",
     "image": "figs/prototyping_pipeline.png",
     "caption": "Perceive -> world -> emit/act, generated from a real spec so labels cannot drift",
     "bullets": [
         "Perceptors turn any-modality inputs into symbolic state",
         "Verified transitions step inside a composite of nested worlds",
         "Objectives (dial-retuned) score; emit/act boundary returns reports and tool-calls"]},
    {"type": "bullets", "title": "A composition algebra for worlds",
     "bullets": [
         "Worlds are values; compose() is closed -- output is itself a world",
         "Children run unmodified; bridges couple, aggregators roll up, bindings inject",
         "Closure, identity, and associativity hold up to namespace renaming",
         "Verification is compositional: verified pieces => verified whole",
         "Turns one n-rule synthesis into n small, independently verified problems"]},
    {"type": "bullets", "title": "Verified reward induction",
     "bullets": [
         "Objective made symmetric to the transition: a verified reward as code",
         "CodeObjective's reward() runs in the same pure-Python sandbox",
         "induce_reward accepts only when it exact-matches held-out rewards",
         "Closes the loop: verified perception + dynamics + reward + planning",
         "The primitive ARC-AGI-3-style goal discovery demands"]},

    {"type": "section", "title": "Prototyping cost & latency"},
    {"type": "bullets", "title": "How fast is prototyping? (E68)",
     "bullets": [
         "Claude Code authored 100 world models from one-line descriptions",
         "6 regulated sectors: health, finance, legal, cyber, energy, agentic-AI",
         "100% validate; median 2.8 min, mean 3.0, p90 3.9, max 6.1",
         "99% (99/100) are behaviorally executable under a random rollout",
         "Hand-authoring a comparable simulator is a days-to-weeks effort"]},
    {"type": "figure", "title": "Atlas of the 100 prototyped worlds (E68/E68b)",
     "image": "figs/world_atlas.png",
     "caption": "One row per world, grouped by sector; all declare perceive and emit boundaries",
     "bullets": [
         "Columns: state size, actions, build minutes, declared boundaries",
         "Exec marks the behavioral audit -- only one recipe fails to evolve state",
         "Generated from per-world records, so it cannot drift from results"]},
    {"type": "statement", "text": "When dynamics are writable, prototyping a correct world model is a minutes-scale, push-button activity."},

    {"type": "section", "title": "Experimental setup"},
    {"type": "bullets", "title": "Worlds with ground truth",
     "bullets": [
         "Three deterministic oracle worlds: sprint, orchard, triage",
         "Oracles are hand-written FunctionTransitions",
         "Synthesized and learned engines compared against them exactly",
         "Coding world: 20 buggy functions + hidden tests, test-execution dynamics",
         "Composition/nesting/changing-rules probed by E30--E32"]},
    {"type": "bullets", "title": "Models, hardware, baselines, statistics",
     "bullets": [
         "All local via Ollama on an Apple-silicon laptop -- no cloud, no fine-tuning",
         "qwen2.5 7b/3b/1.5b, plus llama3.1:8b and gemma2:9b for cross-family",
         "Baseline: LLMTransition -- same backbone predicting each next state",
         "Rate metrics get 95% Wilson CIs; judge test is exact paired McNemar",
         "Seeds fixed; every number regenerates from one pipeline"]},

    {"type": "part", "title": "Results", "subtitle": "Fidelity, latency, and trust"},
    {"type": "figure", "title": "Performance: fidelity and latency (E04, E11)",
     "image": "figs/pres_speed.png",
     "caption": "One verified transition reused at every step -- no compounding error",
     "bullets": [
         "7B-synthesized dynamics exact on 24/24 20-step rollouts; 100% on 10x OOD probes",
         "14,997 steps/s vs 0.32 for the LLM proxy (~47,000x)"]},
    {"type": "figure", "title": "Verifier ablation: correctness gained per gate (E3)",
     "image": "figs/verifier.png",
     "caption": "Blind 0.46 -> behavioral 0.65 -> +critic 0.70 (a +0.24 absolute gain)",
     "bullets": [
         "Syntax-only adds nothing -- this generator's failures parse fine",
         "No 3B generation is bit-exact under any regime",
         "Verification buys correctness margin but cannot replace generator capability"]},
    {"type": "bullets", "title": "Closing the false-accept gap (E62)",
     "bullets": [
         "Single-state smoke-run has a blind spot: later-reached states",
         "On 3 faults clean initially, single-state gate false-accepts 100%",
         "Re-running over branch-covering states drops false-accepts to 0%",
         "Cross-family (E16): Qwen/Llama/Gemma all reach verified acceptance",
         "Gemma-2-9B is rule-perfect on every attempt; seconds per world"]},
    {"type": "figure", "title": "Agents-as-a-judge, controlled (E13+E17)",
     "image": "figs/judge.png",
     "caption": "Judge 85% vs random 78%, first 78%, oracle ceiling 91% over 120 rounds",
     "bullets": [
         "Judge recovers ~half the random-to-oracle gap (McNemar p marginal)",
         "Order-reversal: raw choices match ~57% but accuracy is order-stable",
         "Costs ~4x inference; judges should gate, not replace, verification"]},
    {"type": "figure", "title": "Anatomy of a composite world (E31)",
     "image": "figs/composition.png",
     "caption": "Two countries, each with two cities, compose into a region -- real state values",
     "bullets": [
         "Bridge carries trade under a conservation invariant",
         "Route lets an agent cross and pay a toll; aggregators summarize upward",
         "Binding injects a parent parameter into a child"]},
    {"type": "anim", "diagram": "cliff", "title": "Composition defeats the complexity cliff",
     "still": "figs/composition_cliff.png"},
    {"type": "figure", "title": "What an agent sees (E31)",
     "image": "figs/traversal.png",
     "caption": "Scoped observation: own node full, ancestors as aggregates, neighbors as summaries",
     "bullets": [
         "Its own city fully observable; ancestor levels expose only _agg summaries",
         "Route-adjacent city is a summary card; siblings not observable",
         "Planners reason locally against exact dynamics without the macrostate"]},
    {"type": "figure", "title": "When the rules change, agents move (E33)",
     "image": "figs/dynamic_traversal.png",
     "caption": "Austerity hits at step 9; agent pays the toll, relocates, gains +20 mobility",
     "bullets": [
         "Shared economy enters austerity via PhasedTransition",
         "Greedy agent prices the change and crosses to the growing economy",
         "Both phased and monolithic synthesized code track the switch exactly"]},
    {"type": "figure", "title": "The sprint world: budget allocation (E34)",
     "image": "figs/sprint.png",
     "caption": "20 repair worlds, budget 80; fixed protocol solves 15/20",
     "bullets": [
         "No policy beats the fixed ceiling -- the unsolved tail is capability-bound",
         "Round-robin reaches the plateau in ~a third fewer attempts",
         "Greedy closest-to-passing tarpits on a single task"]},
    {"type": "figure", "title": "Perceive-then-forecast an SIR epidemic (E40)",
     "image": "figs/perception.png",
     "caption": "Perceived world model is exact in and out of distribution; the MLP collapses at 10x scale",
     "bullets": [
         "Day-0 text + ward-photo perceived into S,I,R, then rolled 14 days",
         "Dynamics add zero error, so forecast accuracy equals perception accuracy",
         "E39: this decomposition holds exactly across perception error 0--0.9"]},
    {"type": "figure", "title": "Tunable morality: the moral dial (E8)",
     "image": "figs/pareto.png",
     "caption": "Welfare--fairness frontier swept by lambda; Nash bargaining optimum interior at 0.8",
     "bullets": [
         "All 11 sweep points are Pareto-optimal; fairness monotone in lambda",
         "Values are declared, weighted artifacts -- no retraining to move",
         "Operationalizes the open-specification response to static alignment"]},

    {"type": "section", "title": "Shareable, auditable worlds"},
    {"type": "figure", "title": "Portable world-model specs (E57)",
     "image": "figs/world_specs.png",
     "caption": "5 worlds round-trip losslessly at a few KB; nine components captured",
     "bullets": [
         "from_spec(to_spec(w)) reproduces the original rollout exactly",
         "State, rules, dynamics, perception/emit, objectives, metrics -- all captured",
         "Embedded code is inert unless execution is explicitly opted in"]},
    {"type": "figure", "title": "A generated model card (E57)",
     "image": "figs/world_card.png",
     "caption": "One self-contained SVG rendered from the triage world's spec",
     "bullets": [
         "State-transition automaton with the perceive->world->emit boundary",
         "Panels list schema, actions, dynamics, objectives, rollout, metrics",
         "Also exports to Mermaid and React Flow for interactive use"]},

    {"type": "part", "title": "Applications", "subtitle": "Domains and demonstrations"},
    {"type": "figure", "title": "Emergent economy from composed verified rules (E44)",
     "image": "figs/emergent_economy.png",
     "caption": "6 agents; Gini 0.22 -> 0.001 with redistribution; cooperation lifts welfare",
     "bullets": [
         "Macro (price, inflation, Gini) are aggregators derived from micro leaves",
         "Each phenomenon isolated by toggling one verified rule",
         "Books balance exactly every tick -- gold moves only by faucet minus sink"]},
    {"type": "figure", "title": "A composite corporate world (E48)",
     "image": "figs/corporate_world.png",
     "caption": "5-division, $1500M PaaS as nested CompositeWorld; CEO reallocation is +21%",
     "bullets": [
         "Company > divisions > individuals; revenue aggregates upward",
         "Selfishness trades company growth for a higher promotion Gini",
         "Perception is granularity-bound: promo signal recovered only from 1:1s"]},
    {"type": "figure", "title": "A startup growth world model (E51)",
     "image": "figs/startups.png",
     "caption": "PMF moves value +387%; capital +0%; top decile captures 83% of value",
     "bullets": [
         "Each startup a verified child world; batch aggregates exactly",
         "Only 36% survive -- the venture power law reproduced",
         "Spend cannot substitute for product-market fit"]},
    {"type": "figure", "title": "Relativity as a verified world model (E47)",
     "image": "figs/relativity.png",
     "caption": "Twin returns 4 years younger; GPS correction +38.5 us/day from first principles",
     "bullets": [
         "Time dilation exact; a low-speed learned fit diverges as v -> c",
         "Hafele--Keating east/west shifts land inside the 1971 measurements",
         "Declared, verified law where learned video models miss the physics"]},
    {"type": "figure", "title": "A same-day trading world model (E50)",
     "image": "figs/trading.png",
     "caption": "After cost +15.7% annualized but Sharpe 0.59 < SPY 0.77 -- honest, cost-fragile",
     "bullets": [
         "Real OHLC, walk-forward, no-lookahead, after-cost backtest",
         "Recovers a known +40 bps synthetic edge, so a weak real result is real",
         "Contribution is rigor and auditability, not alpha"]},
    {"type": "figure", "title": "Wavelet denoising as perceive->world->emit (E52)",
     "image": "figs/denoise.png",
     "caption": "Parameter-free wavelet gains +14.1 dB on edges, beating a tuned low-pass",
     "bullets": [
         "Noisy signal -> sparse symbolic state (significant coefficients)",
         "Declared soft-threshold rule; inverse transform emits cleaned signal",
         "Mismatches reported: Fourier wins on smooth, Haar wrong on speech"]},
    {"type": "figure", "title": "A brain as a world-of-worlds (E58)",
     "image": "figs/brain_card.png",
     "caption": "Conscious + unconscious + environment, coupled by retrieve/consolidate/act bridges",
     "bullets": [
         "Working memory, content-addressable long-term memory, environment",
         "Perceive -> retrieve -> think -> act -> observe -> consolidate loop",
         "The whole brain serializes to a spec and round-trips losslessly"]},
    {"type": "figure", "title": "Tree-of-thoughts ReAct with real memory (E58)",
     "image": "figs/brain.png",
     "caption": "Persistent memory reaches optimal L=4; memoryless stays ~22, random flails",
     "bullets": [
         "Persistent unconscious drives steps-to-goal to optimal in a couple episodes",
         "Steps fall with planning depth, plateau once depth reaches the horizon",
         "Bounded simulated lookahead helps up to the goal horizon, no further"]},
    {"type": "figure", "title": "The brain around a frozen model (E59)",
     "image": "figs/brain_arch.png",
     "caption": "Modeled backbone: bare 0.33 -> richest brain 1.00 (+0.68), no change to the LLM",
     "bullets": [
         "Retrieval makes rare-fact questions answerable; best-of-N+verify wins hard ones",
         "Ordering is a consequence of the modeling assumptions, not an empirical finding",
         "With the model frozen, the world model around it is what you optimize"]},
    {"type": "figure", "title": "The perceive->world->emit->act boundary (E60)",
     "image": "figs/io_boundary.png",
     "caption": "Content-addressable recall routes 78% vs Jaccard 70% vs exact-key 0%; resolves 78% end to end",
     "bullets": [
         "JSON/Regex perceptors + gates; MemoryStore; tool and code emitters",
         "Contract gates catch every injected malformed input and out-of-contract output",
         "All components serialize to a spec and round-trip with no LLM in the loop"]},
    {"type": "figure", "title": "Sprint allocation across a capability ladder (E35)",
     "image": "figs/sprint_ladder.png",
     "caption": "Fixed ceiling rises 15 -> 19/20 with capability; greedy tarpit defangs with scale",
     "bullets": [
         "qwen2.5:7b -> deepseek-r1:14b -> gpt-oss:20b -> qwen3-coder:30b",
         "Greedy tarpit is capability-gated; gpt-oss:20b clears all 20",
         "Allocation policy is dominated by base model capability"]},
    {"type": "figure", "title": "Composition yields better representations (E36)",
     "image": "figs/representations.png",
     "caption": "Every monolithic learner collapses on novel combos; the factored composite stays flat",
     "bullets": [
         "Best monolith (gradient boosting) decays from 0.48 to 0.20 by K=5",
         "Collapse holds across kernels, trees, GPs, and a Koopman operator",
         "Factoring the representation -- not scaling the learner -- buys generalization"]},
    {"type": "figure", "title": "Adapting to sudden, unannounced rule changes (E41)",
     "image": "figs/nonstationary.png",
     "caption": "Symbolic monitor re-pins the rule in 1 step; sliding-window lags, frozen never recovers",
     "bullets": [
         "A reservoir's hidden regime jumps at unannounced times",
         "Explicit, identifiable program => a few observations re-pin it exactly",
         "Holds while the changed rule stays in the identifiable family"]},
    {"type": "figure", "title": "Agents traversing connected worlds with changing rules (E42)",
     "image": "figs/agent_traversal.png",
     "caption": "Per-world monitor 0.94 and returns nearly free; shared learner 0.85 pays interference",
     "bullets": [
         "Two non-stationary worlds joined by a toll route; agent hops between",
         "Per-world programs carry a world's rule across an absence intact",
         "A single shared belief cannot hold two worlds at once"]},
    {"type": "figure", "title": "Next-token world models: exact length generalization (E45)",
     "image": "figs/next_token.png",
     "caption": "Induced program exact OOD on 3/3 tasks (1.00); same 30B predicting directly falls to 0.38",
     "bullets": [
         "Parity, dyck, copy: memory a fixed window cannot hold",
         "Synthesize-a-program mode is length-invariant by construction",
         "n-gram and fixed-window MLP both decay with length"]},
    {"type": "figure", "title": "A database for many worlds (E46)",
     "image": "figs/many_worlds.png",
     "caption": "Exact version space over 1e18 worlds in 191 ms; #P boundary surfaced, not hidden",
     "bullets": [
         "Likelihood factorizes over observables -> one small factor per mechanism",
         "Pluggable semiring answers Boolean, counting, and probability queries",
         "Couple w parameters non-separably and the factor grows as d^w"]},
    {"type": "figure", "title": "Path integrals over learning trajectories (E49)",
     "image": "figs/path_integral.png",
     "caption": "Least-action curriculum reuses mastered sub-worlds -- a 6.0x speedup over from-scratch",
     "bullets": [
         "Trajectory weighted by e^(-beta S); reuse the E46 semiring engine",
         "Combinatorially many trajectories summed by DP without enumeration",
         "Different starting roles (SWE, director, CEO) get different optimal paths"]},
    {"type": "figure", "title": "Abstract interpretation: sound, tight bounds (E54)",
     "image": "figs/bounds.png",
     "caption": "Affine bound width 21.5 vs interval 108.6; Monte Carlo tight but unsound",
     "bullets": [
         "Run the world on abstract states -- propagate whole sets forward",
         "Affine domain tracks a/(1-a) cancellation; intervals explode",
         "Gives the world model a worst-case rollout it can certify"]},
    {"type": "figure", "title": "Information geometry: identify the world (E55)",
     "image": "figs/infogeom.png",
     "caption": "Expected info gain identifies the true world in 6.5 probes vs random 9.4 (of 10 worlds)",
     "bullets": [
         "Choose the probe whose outcome carries the most information",
         "Adaptivity: stop re-confirming, separate worlds still in contention",
         "Exact enumerable candidates make identification principled experiment design"]},

    {"type": "part", "title": "Reflection", "subtitle": "Discussion, limitations, what comes next"},
    {"type": "bullets", "title": "Interpretation: a structural trade",
     "bullets": [
         "Learned models buy pixel breadth, pay in compounding error and opacity",
         "Verified code buys exactness, speed, OOD transfer, auditability",
         "Within the symbolic boundary the results are one-sided",
         "The workflow: declare, verify with invariants, probe intent, tighten, recompile",
         "The artifact stays a diffable program at every stage"]},
    {"type": "bullets", "title": "What these worlds enable: world-time compute",
     "bullets": [
         "Verified worlds label trajectories exactly, for free",
         "Fine-tuning on many worlds of a domain lifts generalization to held-out worlds",
         "This is world-time compute -- the subject of the companion paper",
         "Exact, composable worlds are what make it possible",
         "But a world computer is useful whether or not one ever fine-tunes"]},
    {"type": "bullets", "title": "Value alignment as open specification",
     "bullets": [
         "Objectives are declared artifacts -- the welfare--fairness frontier is operational",
         "A weighted sum is one ethical theory (act consequentialism)",
         "Aggregators, side-constraint vetoes, and a moral parliament are distinct objects",
         "Vetoes cannot be simulated by weights (E25)",
         "Open spec manages the specification trap procedurally, does not resolve it"]},
    {"type": "cards", "title": "Limitations",
     "cards": [
         {"head": "Scope", "icon": "grid", "text": "Symbolic worlds only"},
         {"head": "Complexity", "icon": "lock", "text": "Monolithic breaks past ~8 rules"},
         {"head": "Scale", "icon": "flask", "text": "20 repair tasks, 3 oracle worlds"},
         {"head": "Trust", "icon": "shield", "text": "Judge marginal; self-check is a screen"}]},
    {"type": "bullets", "title": "Frozen perceptual features don't control cartpole (E67)",
     "bullets": [
         "The perceptual species' best shot on cartpole still scores 0%",
         "Five ways to bolt a controller onto frozen V-JEPA-2/DINOv2 all score 0",
         "Yet a probe recovers the state: R2(sin theta) = 0.95",
         "Strong frozen features are necessary but not sufficient for control",
         "End-to-end task training, not better perception, closes the gap"]},

    {"type": "section", "title": "Conclusion"},
    {"type": "statement", "text": "Make the model a program, verify the program, and keep the values dialable -- an orthogonal path to scaling parameters until hallucination is suppressed."},
    {"type": "bullets", "title": "Takeaways and next steps",
     "bullets": [
         "A training-free symbolic world model is bit-exact where learned dynamics compound error",
         "Composition defeats the complexity cliff; the boundary is measured, not hidden",
         "100 worlds in minutes on a laptop; portable, auditable, shareable specs",
         "Next: compositional synthesis, standard-scale coding, hybrid perception-to-symbol",
         "All code, 100 recipes, and 79 experiments regenerate from one repository"]},
]
