TITLE = "World-Time Computing"
SUBTITLE = "A new way to learn: build practice worlds and turn computer time into endless practice with guaranteed-correct answers"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The whole talk on one page"},
    {"type": "part", "title": "Why we did this", "subtitle": "Making practice out of thin air"},
    {"type": "steps", "title": "The problem: real practice is hard to get",
     "steps": [
         {"head": "Needs examples", "text": "AI gets good only after many real examples with the right answers"},
         {"head": "Rare and costly", "text": "In most areas those examples are rare and expensive"},
         {"head": "A cheap fix", "text": "We found a cheap way to make them"},
         {"head": "The trick", "text": "When a world's rules can be written as code, we simulate the practice"}]},
    {"type": "compare", "title": "Two kinds of world model",
     "left": {"head": "Picture kind", "icon": "atom",
              "items": ["Big learned nets guess pixels or video (Dreamer, Genie, Sora)",
                        "Need tons of data",
                        "Small mistakes pile up",
                        "You can't read what's inside"]},
     "right": {"head": "Code kind (CWMs)", "icon": "code",
               "items": ["Rules are a plain program you can read, over simple facts",
                         "An AI writes the program",
                         "We check it is right",
                         "Then it runs exactly and needs no training data"]}},
    {"type": "statement",
     "text": "Picture-based systems try to learn things nobody can put into words. OpenWorld writes down the rules that CAN be put into words -- and then checks them."},
    {"type": "compare", "title": "Two things have to be true for this to work",
     "left": {"head": "Never wrong", "icon": "shield",
              "items": ["Practice worlds' rules are checked code, not a guess",
                        "Reads cleanly, runs safely, keeps promises, passes a reviewer"]},
     "right": {"head": "Cheap to build", "icon": "bolt",
               "items": ["You need many -- so each must be cheap to build",
                         "OpenWorld builds a checked world in minutes"]}},
    {"type": "steps", "title": "What we contribute",
     "steps": [
         {"head": "Compute to practice", "text": "Turn computer time into practice, plus a skill that carries to new worlds"},
         {"head": "Why checked code", "text": "It runs exactly, so small mistakes never pile up"},
         {"head": "Repeatable toolkit", "text": "The OpenWorld toolkit -- 79 experiments, fixed random seeds"}]},

    {"type": "section", "title": "Setting up the problem"},
    {"type": "quadrant", "title": "Worlds made of plain facts",
     "cells": [
         {"head": "Plain facts", "icon": "grid", "text": "State is simple data; moves are a short list; rules can be spelled out"},
         {"head": "What it covers", "icon": "stack", "text": "Triage, bargaining, portfolios, sprints, fixing programs"},
         {"head": "Where it stops", "icon": "lock", "text": "Not picture-heavy worlds -- that is the boundary"},
         {"head": "The enemy", "icon": "shield", "text": "A wrong model: made-up moves, code that is quietly wrong"}]},
    {"type": "hub", "title": "What a world model is, plainly",
     "center": "A world model",
     "spokes": [
         {"label": "States & moves", "icon": "nested"},
         {"label": "You spell out", "icon": "compass"},
         {"label": "Tool writes rule", "icon": "code"},
         {"label": "Proves promises", "icon": "check"}]},
    {"type": "anim", "diagram": "compounding", "title": "Checked code stays right no matter how far you go",
     "still": "figs/hero.png"},

    {"type": "section", "title": "How we ran the tests"},
    {"type": "timeline", "title": "The worlds and the models",
     "items": [
         {"t": "Known-answer", "text": "Three -- sprint, orchard, triage (we wrote the true rules)"},
         {"t": "Coding world", "text": "20 buggy functions to fix; running the tests decides what happens"},
         {"t": "Local models", "text": "qwen2.5 1.5B/3B/7B, plus Llama-3.1-8B, Gemma2-9B"},
         {"t": "Training", "text": "Extra-training runs: one cloud A100, low-memory 4-bit method"}]},
    {"type": "compare", "title": "What we compared against, and how we scored",
     "left": {"head": "What we compared", "icon": "gauge",
              "items": ["Guessing baseline: same model guessing each next step directly",
                        "A trained net and a nearest-example lookup on 100 / 1k / 10k steps"]},
     "right": {"head": "How we scored", "icon": "target",
               "items": ["Exact match, first wrong step, end error; pass@k for fixing code",
                         "95% ranges; every number comes back out of one script"]}},

    {"type": "part", "title": "The core idea", "subtitle": "Checked code + turning compute into practice"},
    {"type": "stats", "title": "The whole idea in three numbers",
     "items": [{"value": "24/24", "label": "runs exactly right (code)", "icon": "check"},
               {"value": "0/24", "label": "runs exactly right (guessing)", "icon": "gauge"},
               {"value": "+29 pts", "label": "boost on new worlds at 0.5B", "hi": True, "icon": "bars"}]},
    {"type": "figure", "title": "Checked code stops mistakes from piling up",
     "image": "figs/hero.png",
     "caption": "A: code stays exact all the way; guessing drifts off by about step 2.3. B: the payoff of making practice worlds.",
     "bullets": [
         "Code (blue) matches the true answer exactly across all 20 steps",
         "Guessing each step (orange) first drifts around step 2.3 and never finishes exactly",
         "B: extra training on 60 checked worlds raises the score on worlds it never trained on",
         "The smallest models gain the most: +29 pts at 0.5B, +3 at 32B"]},
    {"type": "figure", "title": "Head-to-head: how true the rules stay (E1/E4/E11)",
     "image": "figs/pres_exact.png",
     "caption": "Right once means right at every depth; the step-by-step guesser never finishes exactly",
     "bullets": [
         "Code runs at about 15,000 steps a second; the guesser at 0.32 steps a second",
         "On surprise cases: code is 100% exact with zero practice steps"]},
    {"type": "statement",
     "text": "The claim you can trust is the exact-match gap, not the exact step where guessing drifts -- how fast mistakes pile up depends on each world."},

    {"type": "section", "title": "Turning Compute Into Practice: Learning Across Many Worlds"},
    {"type": "anim", "diagram": "worldtime", "title": "What this practice-making really is",
     "still": "figs/crossworld.png"},
    {"type": "figure", "title": "Inside one diagnosis world (E74)",
     "image": "figs/diagnosis_world.png",
     "caption": "A hidden disease gives off symptoms; the agent works backwards to name the disease.",
     "bullets": [
         "Each specialty is a tiny simulator with a hidden cause and a known answer",
         "The agent uses its own checked world as the source of truth",
         "Practice on many specialties, then test on ones it never saw",
         "This forces it to learn the real skill, not just memorize"]},
    {"type": "figure", "title": "It really generalizes -- and small models gain most",
     "image": "figs/pres_smallmodel.png",
     "caption": "A boost at every model size on worlds it never saw; the smaller the model, the bigger the boost",
     "bullets": [
         "0.5B: 37% -> 66%; 32B: 78% -> 81%, closing on the 86% you get when told the rules",
         "Worlds that share no common skill (E71/E73) give no carry-over"]},

    {"type": "part", "title": "Scaling and real data", "subtitle": "More worlds, correct answers, real tasks"},
    {"type": "figure", "title": "More worlds keeps helping (E76)",
     "image": "figs/world_count.png",
     "caption": "Score on unseen worlds versus how many worlds you practice on; still rising at 512.",
     "bullets": [
         "Too few worlds hurts (below 48%) -- it overfits a narrow slice",
         "After that the score keeps climbing, no flattening out",
         "Still rising at 512 worlds: 59% (+10 pts), heading toward the 69% you get when told the rules",
         "The number of worlds is a real knob you can turn"]},
    {"type": "figure", "title": "Correct answers are the real lever (E78b)",
     "image": "figs/noise_ablation.png",
     "caption": "Spoil a fraction p of the training answers; the score drops steadily.",
     "bullets": [
         "256 worlds, held fixed; only the training answers get corrupted at rate p",
         "All correct (p=0): 35%; all wrong (p=1): 19%, at or below the floor",
         "Correct answers -- not just having lots of tasks -- is what drives it",
         "This is what sets our approach apart from just shuffling the tasks"]},
    {"type": "bigstat", "title": "A family of coding worlds (E77)",
     "value": "164", "sub": "write-this-function worlds, each checked by its own tests",
     "points": [
         "7B pass@5 rises 84% -> 95% at every size",
         "On HumanEval it hurts the single greedy try (78% -> 70%)",
         "But helps pass@5 (87% -> 91%) from just 164 worlds"]},

    {"type": "section", "title": "Real Data: Practice Worlds on ARC-AGI"},
    {"type": "figure", "title": "How we train on one checked world (E80)",
     "image": "figs/arc_method.png",
     "caption": "An ARC puzzle becomes many correctly-answered rows, then extra training on a frozen 4-bit Qwen2.5-7B.",
     "bullets": [
         "Each ARC puzzle is a world with a hidden rule shown by examples",
         "Rotating and recoloring keeps the rule but makes endless correct rows",
         "Two strict tests: a new-puzzle ladder, and practicing on each world at answer time",
         "The spoiled-answer version is the control that tells the difference"]},
    {"type": "figure", "title": "Practice worlds on real ARC-AGI (E80)",
     "image": "figs/arc.png",
     "caption": "Practicing on each world at answer time raises exact matches; carrying skill to new puzzles stays weak.",
     "bullets": [
         "Cold start 2% -> light practice 8% -> heavy practice 10% (+8 pts) with more compute",
         "Spoiled examples fall to 2%, back down at the cold-start floor",
         "The boost needs correct answers -- the model learns each real rule",
         "Carry-over to new puzzles is weak (3% -> 5%): every ARC rule is brand new"]},
    {"type": "figure", "title": "Across real tasks and kinds of data (E80)",
     "image": "figs/worldtime_domains.png",
     "caption": "It scales on plain-fact tasks and stalls on vision; Bongard picture puzzles stay at a coin flip.",
     "bullets": [
         "List Functions: 35% -> 66% -> 69% (heavy); spoiled 3%",
         "CLRS algorithms: 9% -> 13% -> 17%; spoiled 4%",
         "Biggest gains on short rules, smallest on long step-by-step algorithms",
         "Bongard picture puzzles: flat at a coin flip (46/48/52%) -- the vision wall"]},

    {"type": "section", "title": "A Skill That Carries to New Worlds"},
    {"type": "figure", "title": "One skill across many worlds, List Functions (E84)",
     "image": "figs/crossworld.png",
     "caption": "One shared add-on trained on 128 separate worlds works on 60 worlds it never saw.",
     "bullets": [
         "40% (range [35,45]) on worlds it never saw",
         "The spoiled-answer control gets only 6% -- a +34-pt gap that needs correct answers",
         "The gap is real rule-figuring carrying over, not just formatting",
         "The new idea, shown on data we did not make ourselves"]},
    {"type": "figure", "title": "The carry-over grows with more worlds (E84)",
     "image": "figs/crossworld_ladder.png",
     "caption": "Score on unseen worlds rises 29% -> 49%, then levels off near 64 worlds.",
     "bullets": [
         "Rises from 29% at 16 worlds to a 49% peak by 64 worlds",
         "The spoiled-answer control stays flat",
         "A rise-then-level-off curve on real data",
         "More checked worlds means more carry-over"]},
    {"type": "steps", "title": "A simple pattern we noticed (E80)",
     "steps": [
         {"head": "Tapering curve", "text": "score(c) = base + (top - base)(1 - e^{-c/kappa}); holds for a non-AI program-builder too"},
         {"head": "The ceiling", "text": "The top depends on pinning the rule down and reaching it, and how much room is left"},
         {"head": "Small dose predicts", "text": "A quick small dose forecasts the eventual top (Spearman 0.73-0.98)"},
         {"head": "Harder needs more", "text": "Worlds to reach 90%: List Functions 3, ARC 9, CLRS 15"}]},

    {"type": "part", "title": "Where it breaks", "subtitle": "Where it stops working, and why"},
    {"type": "figure", "title": "Different wording doesn't carry over (E81)",
     "image": "figs/frame_invariance.png",
     "caption": "Practicing in other languages doesn't beat a cold start on either model.",
     "bullets": [
         "One problem in 5 languages; practice on some, test on a held-out language",
         "Strong coder flat (28% -> 30%); weak one drops (29% -> 27%)",
         "Only a weak correct-answers ordering survives (correct beats spoiled)",
         "A new language acts like its own separate skill -- an honest limit"]},
    {"type": "figure", "title": "The mix-and-retry loop (E82)",
     "image": "figs/hybrid_loop.png",
     "caption": "Use the checked world to make examples, plus a check-and-try-again safety net on HumanEval-X.",
     "bullets": [
         "Pre-baking examples helps a strong model (80% -> 85%) but hurts a weak one (57% -> 50%)",
         "The mix-and-retry loop lifts both: Qwen 90% (+10), Llama 65% (+8)",
         "The weak model leans on the checker more (2.65 vs 1.45 tries per problem)",
         "Just using the checker as a yes/no judge is enough -- the safe default"]},

    {"type": "section", "title": "Against Trained and Picture-Based Rules"},
    {"type": "figure", "title": "Trained baselines vs a zero-practice program (E12)",
     "image": "figs/learned.png",
     "caption": "A trained net and a nearest-example lookup on K steps; neither works on surprise cases.",
     "bullets": [
         "With 10,000 steps the trained net hits only 50% on familiar cases, 0% on 10x-out cases",
         "The written program: 100% on both, from zero practice steps",
         "Nearest-example lookup replays known runs (8/8) but scores 30% on new branches",
         "Surprise cases and new branches, not replaying known runs, show real quality"]},
    {"type": "figure", "title": "Bigger models don't figure rules out better from examples (E38)",
     "image": "figs/induction_scale.png",
     "caption": "Figuring rules from examples alone stays flat across three model families.",
     "bullets": [
         "From examples alone (no rule text): 0.43 (7B), 0.33 (30B coder), 0.43 (gpt-oss)",
         "None comes near the 1.00 you get when handed the rule text",
         "Every model does the same on familiar and 10x-out cases",
         "The examples just don't pin the rule down -- it's not about model size"]},
    {"type": "figure", "title": "Trying moves beats what size can't (E43)",
     "image": "figs/active_induction.png",
     "caption": "Picking smart moves to test beats just watching.",
     "bullets": [
         "Smart poking finds the exact rule in 11.2 steps vs 14.7 by just watching",
         "Just watching never nails 2 of 5 tricky rules within budget",
         "Smart poking (knowing nothing) matches a see-everything ideal (11.2 vs 11.6)",
         "When examples aren't enough, choose which moves to test"]},
    {"type": "figure", "title": "The complexity cliff (E20)",
     "image": "figs/complexity.png",
     "caption": "How often the build succeeds versus how many tangled rules you ask for.",
     "bullets": [
         "R=4: 1.00; R=8: 0.53; R=12: 0.25; R=16: 0.15",
         "One-shot 7B building gets shaky past about 8 tangled rules",
         "The current limit at this model size",
         "Points to building it piece by piece -- one expert per rule"]},

    {"type": "section", "title": "From Getting It Right to Making Choices"},
    {"type": "quadrant", "title": "Planning through a checked world (E22)",
     "cells": [
         {"head": "Look 3 ahead", "icon": "route", "text": "Look 3 moves ahead, then do the best move in the real world"},
         {"head": "Checked equals true", "icon": "check", "text": "Planning through the checked program scores 7.5 -- same as the true world"},
         {"head": "Baselines", "icon": "gauge", "text": "Rule of thumb 5.0; random 3.8; a whole game planned in 0.03 s"},
         {"head": "Guessing = 0.0", "icon": "bolt", "text": "Planning through the guessing model -- worse than no model at all"}]},
    {"type": "compare", "title": "The showdown (E63/E65/E67)",
     "left": {"head": "Checked code", "icon": "check",
              "items": ["6 runnable models on 2 plain-fact tasks: the checked code is exact and best",
                        "MiniGrid DoorKey: OpenWorld solves it cold in an 11-step plan"]},
     "right": {"head": "Learned models", "icon": "gauge",
               "items": ["Every learned model drops to 0% exact on 10x-out cases",
                         "DreamerV3 needs ~9,640 tries; V-JEPA-2 can't steer at all"]}},

    {"type": "part", "title": "Stepping back", "subtitle": "Discussion, limits, wrap-up"},
    {"type": "steps", "title": "Isn't this just extra training?",
     "steps": [
         {"head": "Yes, but", "text": "Under the hood it's ordinary extra training; the point is where the data comes from"},
         {"head": "Compute to data", "text": "A correct world model turns compute into endless correct training data"},
         {"head": "Earns the name", "text": "Two things: it needs correct answers, and the skill carries to new worlds"},
         {"head": "Honest limit", "text": "Where neither holds, it's just costly extra training -- and we say so"}]},
    {"type": "bigstat", "title": "We measured the unit of practice (E85)",
     "value": "+12 pts", "sub": "in-range: full-path 70% vs final-answer 58%",
     "points": [
         "The unit = one step (state, move, next state), not a final answer",
         "Run longer than trained, final-answer catches up (75% vs 68%)",
         "Stringing step guesses brings back the pile-up on the learned side"]},
    {"type": "contrast", "title": "When is it worth it? Short reasoning",
     "before": {"head": "Wins", "text": "A few steps over facts you can spell out -- short rule-figuring, small grid changes, planning a few moves ahead"},
     "after": {"head": "Fades", "text": "Longer reasoning (CLRS traces, more than 8 tangled rules); long, picture-heavy problems go to the learned models"}},
    {"type": "hub", "title": "Three ways to use a checked world model",
     "center": "Checked world",
     "spokes": [
         {"label": "As a tool", "icon": "gear"},
         {"label": "Practice one world", "icon": "flask"},
         {"label": "Practice many", "icon": "nested"},
         {"label": "Mix", "icon": "atom"}]},
    {"type": "quadrant", "title": "Where it falls short",
     "cells": [
         {"head": "Scope", "icon": "grid", "text": "Plain facts, not pictures"},
         {"head": "Complexity", "icon": "lock", "text": "Cliff past about 8 rules"},
         {"head": "Wobble", "icon": "scan", "text": "Some numbers from one run"},
         {"head": "Stats", "icon": "bars", "text": "No group-wide correction"}]},

    {"type": "section", "title": "Wrap-up"},
    {"type": "statement",
     "text": "Make the model a program, check the program, and keep its goals adjustable -- a different road than just piling on more parameters until the guessing stops."},
    {"type": "cards", "title": "What to remember",
     "cards": [
         {"head": "Exact", "icon": "check", "text": "Checked code is exact where learned ones let mistakes pile up"},
         {"head": "Plans like truth", "icon": "route", "text": "Plans as well as the true world; planning through a guesser is worse than nothing"},
         {"head": "Carries over", "icon": "nested", "text": "Practicing across many checked worlds helps on worlds it never saw"},
         {"head": "Next", "icon": "target", "text": "Build piece by piece, scale up coding worlds, connect pictures to plain facts"}]},
]
