TITLE = "An Introduction to World Computing"
SUBTITLE = "Build small programs that copy a world's rules, check they are right, snap them together, and run them"
AUTHOR = "Jim Schwoebel — Quome / OpenWorld"
VENUE = "github.com/quome-cloud/openworld"

slides = [
    {"type": "agenda", "title": "The whole talk on one map"},
    {"type": "part", "title": "Why bother", "subtitle": "From computing to computing whole worlds"},
    {"type": "stats", "title": "Building a checked world, fast",
     "items": [{"value": "100", "label": "toy worlds, 6 fields", "icon": "nested"},
               {"value": "2.8 min", "label": "typical time to build one", "hi": True, "icon": "flask"},
               {"value": "47,000×", "label": "faster than asking the model each step", "icon": "bolt"}]},
    {"type": "bullets", "title": "What is a world computer?",
     "bullets": [
         "A machine that builds, checks, snaps together, and runs pretend worlds",
         "The rules are plain code you can read and test -- not a black-box trained blob",
         "Old-style computing made math cheap and easy to inspect",
         "World computing wants to do the same thing for whole worlds",
         "The basic job: given where you are and what you do, say what happens next"]},
    {"type": "compare", "title": "Two kinds of world models",
     "left": {"head": "The picture-guessing kind", "icon": "atom",
              "items": ["Guesses pixels (Dreamer, Sora)", "Needs mountains of data", "Small mistakes pile up", "You can't read the insides"]},
     "right": {"head": "The plain-code kind", "icon": "code",
               "items": ["A readable program over facts", "The model writes it, then we check it", "Right at every step, no matter how far", "You can read the source"]}},
    {"type": "bullets", "title": "Why we want checked code",
     "bullets": [
         "The win isn't a clever new rule -- the model often already knows the rule",
         "The win is running that rule exactly and fast, as a tool the agent can call",
         "It's exact: no piling-up mistakes; a trained rule rots as (1-e)^t over time",
         "Plain code runs way faster than asking the model at every single step",
         "PyTorch didn't invent new models -- it made them quick to try out"]},
    {"type": "anim", "diagram": "worldmodel", "title": "World, action, agent, and the run",
     "still": "figs/prototyping_pipeline.png"},
    {"type": "figure", "title": "The world computer, measured on cost, speed, and quality",
     "image": "figs/world_computer.png",
     "caption": "One agent writes checked, ready-to-run worlds; plain checked code runs about 47,000x faster than asking the model each step",
     "bullets": [
         "A: 100 worlds built, typically 2.8 min each (9 out of 10 under 3.9)",
         "B: checked code runs 14,997 steps a second vs 0.32 when the model guesses each step",
         "C: 100% pass the shape check; 99% actually run and behave"]},
    {"type": "bullets", "title": "What we add",
     "bullets": [
         "The idea of world computing, plus a way to snap worlds together that keeps the checking",
         "OpenWorld: spell out the world, check the code, turn goals up or down with dials",
         "Building: 100 worlds, 6 fields, minutes each, on an ordinary laptop",
         "Running: full-speed, exact, readable runs",
         "Testing, trust checks, and small shareable files anyone can inspect"]},

    {"type": "part", "title": "The system", "subtitle": "OpenWorld: the parts, the relay, and snapping worlds together"},
    {"type": "bullets", "title": "Six parts you can test one by one",
     "bullets": [
         "World: what the facts are, what you can do, the rules, and a swappable rules-engine",
         "Three engines: checked code, the model guessing (our yardstick), and a known-right answer",
         "Agent: either the model planning, or a simple fixed strategy",
         "Goals and Dials: state what you care about and how much",
         "The run, the tuner, and the judge -- all on a local model, no extra software needed"]},
    {"type": "flow", "title": "The write, generate, check relay",
     "steps": ["State it", "Generate", "Check 1: does it parse", "Check 2: run it safe", "Check 3: critic", "Accept"],
     "icons": ["grid", "code", "check", "shield", "gear", "check"]},
    {"type": "figure", "title": "One plain-code world, start to finish",
     "image": "figs/prototyping_pipeline.png",
     "caption": "See -> world -> report/act, all built from a real spec so the labels can't drift",
     "bullets": [
         "Sensors turn any kind of input into plain facts and numbers",
         "Checked rules step forward inside a stack of nested worlds",
         "Goals (re-set by dials) score it; the see-and-act edge returns reports and tool calls"]},
    {"type": "bullets", "title": "Build big worlds from small checked pieces",
     "bullets": [
         "Worlds are just values; snap two together and you still get a world",
         "The pieces run untouched; bridges link them, roll-ups summarize, injections pass values in",
         "Snapping stays clean: same in, same out, and grouping doesn't matter (once names line up)",
         "The checking carries over: checked pieces make a checked whole",
         "Turns one big n-rule job into n small jobs you can check on their own"]},
    {"type": "bullets", "title": "Writing the reward as checked code too",
     "bullets": [
         "Make the goal match the rules: a reward you can read and check, written as code",
         "The reward code runs in the same safe little Python box as the rules",
         "We only accept it when it exactly matches rewards we held back to test with",
         "Now the whole loop is checked: seeing, rules, reward, and planning",
         "Exactly the piece an ARC-AGI-3-style 'figure out the goal' puzzle needs"]},

    {"type": "section", "title": "How much it costs and how fast it is to build"},
    {"type": "bullets", "title": "How fast is building? (E68)",
     "bullets": [
         "Claude Code wrote 100 world models from one-line descriptions",
         "6 careful fields: health, finance, law, cyber, energy, AI agents",
         "100% pass the shape check; typical build 2.8 min, average 3.0, most under 3.9, worst 6.1",
         "99 of 100 actually run and change state under random play",
         "Hand-building a similar simulator would take days to weeks"]},
    {"type": "figure", "title": "A map of all 100 built worlds (E68/E68b)",
     "image": "figs/world_atlas.png",
     "caption": "One row per world, grouped by field; every one spells out how it sees and reports",
     "bullets": [
         "Columns: how much state, how many actions, minutes to build, and its edges",
         "The 'run' mark is the behavior check -- only one recipe fails to move at all",
         "Made straight from each world's record, so it can't drift from the results"]},
    {"type": "statement", "text": "When you can just write the rules, building a correct world model becomes a minutes-long, push-a-button job."},

    {"type": "section", "title": "How we set up the tests"},
    {"type": "bullets", "title": "Worlds where we know the true answer",
     "bullets": [
         "Three simple known-answer worlds: sprint, orchard, triage",
         "The known answers are hand-written rules we trust",
         "We compare the model-written and trained engines against them exactly",
         "A coding world: 20 buggy functions with hidden tests, run-the-tests rules",
         "Snapping, nesting, and changing rules are tested in E30 through E32"]},
    {"type": "bullets", "title": "Models, machine, yardstick, and stats",
     "bullets": [
         "All run locally on an Apple-chip laptop -- no cloud, no extra training",
         "qwen2.5 7b/3b/1.5b, plus llama3.1:8b and gemma2:9b to check across families",
         "Yardstick: the same model just guessing each next step",
         "Rates get 95% error bars; the judge test uses a strict paired check",
         "Seeds fixed; every number rebuilds itself from one pipeline"]},

    {"type": "part", "title": "Results", "subtitle": "Accuracy, speed, and trust"},
    {"type": "figure", "title": "Quality and speed (E04, E11)",
     "image": "figs/pres_speed.png",
     "caption": "One checked rule reused at every step -- so mistakes never pile up",
     "bullets": [
         "Code the 7B model wrote was exact on 24/24 20-step runs; 100% even on 10x situations it never saw",
         "14,997 steps a second vs 0.32 when the model guesses each step (about 47,000x)"]},
    {"type": "figure", "title": "What each check buys you (E3)",
     "image": "figs/verifier.png",
     "caption": "No check 0.46 -> run-it check 0.65 -> add a critic 0.70 (a +0.24 jump)",
     "bullets": [
         "A parse-only check adds nothing -- this model's mistakes still parse fine",
         "No 3B model ever gets it exactly right, under any setup",
         "Checking buys extra correctness but can't make up for a weak writer"]},
    {"type": "bullets", "title": "Closing the 'wrongly accepted' gap (E62)",
     "bullets": [
         "A single quick test has a blind spot: states you only reach later",
         "On 3 faults that look clean at first, the single test wrongly passes them 100% of the time",
         "Re-running across states that hit every branch drops wrong passes to 0%",
         "Across families (E16): Qwen, Llama, and Gemma all reach a checked pass",
         "Gemma-2-9B gets the rules perfect every try; seconds per world"]},
    {"type": "figure", "title": "The model as a judge, fair test (E13+E17)",
     "image": "figs/judge.png",
     "caption": "Judge 85% vs coin-flip 78%, first-one 78%, best-possible 91% over 120 rounds",
     "bullets": [
         "The judge wins back about half the gap from coin-flip to best-possible (barely significant)",
         "Flip the order and raw picks agree only ~57%, but accuracy holds steady",
         "It costs about 4x more to run; judges should screen, not replace, real checking"]},
    {"type": "figure", "title": "Inside a snapped-together world (E31)",
     "image": "figs/composition.png",
     "caption": "Two countries, each with two cities, snap into a region -- with real numbers",
     "bullets": [
         "A bridge carries trade, and the totals always balance",
         "A route lets an agent cross and pay a toll; roll-ups summarize upward",
         "An injection hands a parent's setting down to a child"]},
    {"type": "anim", "diagram": "cliff", "title": "Snapping pieces beats the complexity wall",
     "still": "figs/composition_cliff.png"},
    {"type": "figure", "title": "What an agent actually sees (E31)",
     "image": "figs/traversal.png",
     "caption": "Limited view: your own spot in full, parents as summaries, neighbors as short cards",
     "bullets": [
         "Its own city in full; higher levels show only rolled-up summaries",
         "The city across the route is a summary card; siblings it can't see",
         "Planners think locally against exact rules, without the big picture"]},
    {"type": "figure", "title": "When the rules change, agents move (E33)",
     "image": "figs/dynamic_traversal.png",
     "caption": "Belt-tightening hits at step 9; the agent pays the toll, moves, and gains +20 mobility",
     "bullets": [
         "A shared economy switches into belt-tightening at a set time",
         "A greedy agent prices the change and crosses to the growing economy",
         "Both the switching code and one big block of code track the change exactly"]},
    {"type": "figure", "title": "The sprint world: splitting a budget (E34)",
     "image": "figs/sprint.png",
     "caption": "20 repair worlds, budget 80; a fixed plan solves 15/20",
     "bullets": [
         "No strategy beats the fixed ceiling -- the leftover tasks are just too hard",
         "Round-robin reaches that ceiling in about a third fewer tries",
         "Greedy 'closest to passing' gets stuck grinding one task"]},
    {"type": "figure", "title": "See first, then forecast an outbreak (E40)",
     "image": "figs/perception.png",
     "caption": "The see-then-run model is exact both in and out of familiar range; the trained net falls apart at 10x scale",
     "bullets": [
         "Read day-0 text plus a ward photo into well, sick, recovered counts, then run 14 days",
         "The rules add zero error, so the forecast is only as good as the first reading",
         "E39: this split holds exactly even as reading errors climb from 0 to 0.9"]},
    {"type": "figure", "title": "Turning the morality dial (E8)",
     "image": "figs/pareto.png",
     "caption": "Trade-off between overall good and fairness, swept by a dial; the fair middle sits at 0.8",
     "bullets": [
         "All 11 dial points are best-possible trade-offs; more dial = more fairness, steadily",
         "The values are just stated, weighted settings -- no retraining to shift them",
         "This is the 'state your values openly' answer to fixed, baked-in values"]},

    {"type": "section", "title": "Worlds you can share and inspect"},
    {"type": "figure", "title": "Small shareable world files (E57)",
     "image": "figs/world_specs.png",
     "caption": "5 worlds save and reload with no loss at a few KB each; nine parts captured",
     "bullets": [
         "Save a world, reload it, and it runs exactly the same as before",
         "Facts, rules, dynamics, seeing/reporting, goals, and scores -- all saved",
         "Any embedded code sits dead unless you clearly turn running on"]},
    {"type": "figure", "title": "An auto-made model card (E57)",
     "image": "figs/world_card.png",
     "caption": "One self-contained picture drawn straight from the triage world's file",
     "bullets": [
         "A map of the states with the see -> world -> report edge marked",
         "Panels list the facts, actions, rules, goals, a sample run, and scores",
         "Also exports to Mermaid and React Flow so you can click around it"]},

    {"type": "part", "title": "Where it's useful", "subtitle": "Fields and demos"},
    {"type": "figure", "title": "An economy that grows out of snapped checked rules (E44)",
     "image": "figs/emergent_economy.png",
     "caption": "6 players; inequality drops 0.22 -> 0.001 with sharing; teaming up raises everyone's lot",
     "bullets": [
         "Big-picture numbers (price, inflation, inequality) are roll-ups of the little players",
         "Each effect is isolated by flipping one checked rule on or off",
         "The books balance to the penny every tick -- gold only enters and leaves through set taps"]},
    {"type": "figure", "title": "A whole company as nested worlds (E48)",
     "image": "figs/corporate_world.png",
     "caption": "A 5-division, $1500M company as nested worlds; the CEO reshuffling budgets is +21%",
     "bullets": [
         "Company > divisions > people; revenue adds up the ladder",
         "Being selfish trades company growth for lopsided promotions",
         "You only spot the promotion signal from the one-on-ones, not the top view"]},
    {"type": "figure", "title": "A startup-growth world (E51)",
     "image": "figs/startups.png",
     "caption": "Finding product fit is +387% value; more cash is +0%; the top tenth grab 83% of the value",
     "bullets": [
         "Each startup is its own checked world; the batch adds up exactly",
         "Only 36% survive -- the well-known venture power law shows up",
         "Spending can't stand in for actually fitting the market"]},
    {"type": "figure", "title": "Relativity as a checked world (E47)",
     "image": "figs/relativity.png",
     "caption": "The traveling twin comes back 4 years younger; the GPS fix +38.5 us/day, all from first principles",
     "bullets": [
         "Time-slowing is exact; a low-speed trained fit drifts off as speed nears light-speed",
         "The famous 1971 flying-clock east/west shifts land inside what was measured",
         "A stated, checked law where trained video models miss the physics"]},
    {"type": "figure", "title": "A one-day trading world (E50)",
     "image": "figs/trading.png",
     "caption": "After costs +15.7% a year but its risk-adjusted score 0.59 < the market's 0.77 -- honest, cost-fragile",
     "bullets": [
         "Real prices, walked forward, no peeking ahead, costs included",
         "It recovers a known fake +40 bps edge, so a weak real result is real",
         "The point is being rigorous and inspectable, not beating the market"]},
    {"type": "figure", "title": "Cleaning up a signal, see -> world -> report (E52)",
     "image": "figs/denoise.png",
     "caption": "A knob-free wavelet method gains +14.1 dB on edges, beating a tuned blur",
     "bullets": [
         "Noisy signal -> a short list of the important pieces",
         "A stated 'trim the small stuff' rule; then rebuild the clean signal",
         "We report where it loses too: Fourier wins on smooth, one method is wrong on speech"]},
    {"type": "figure", "title": "A brain as a world made of worlds (E58)",
     "image": "figs/brain_card.png",
     "caption": "Conscious, unconscious, and the environment, linked by recall/save/act bridges",
     "bullets": [
         "Short-term memory, recall-by-content long-term memory, and the environment",
         "A loop: see -> recall -> think -> act -> watch -> save",
         "The whole brain saves to a file and reloads with no loss"]},
    {"type": "figure", "title": "A think-ahead ReAct agent with real memory (E58)",
     "image": "figs/brain.png",
     "caption": "With memory it hits the best score at depth 4; no-memory stalls around 22, random flails",
     "bullets": [
         "Keeping the unconscious memory drops steps-to-goal to the best in a couple tries",
         "Steps fall as you plan deeper, then flatten once you plan far enough ahead",
         "Thinking ahead helps up to the goal's distance, and no further"]},
    {"type": "figure", "title": "The brain wrapped around a frozen model (E59)",
     "image": "figs/brain_arch.png",
     "caption": "Same model inside: bare 0.33 -> fullest brain 1.00 (+0.68), without touching the model",
     "bullets": [
         "Recall makes rare-fact questions answerable; try-many-and-check wins the hard ones",
         "This order follows from the setup by design, it isn't a surprise finding",
         "With the model frozen, the brain around it is the thing you improve"]},
    {"type": "figure", "title": "The see -> world -> report -> act edge (E60)",
     "image": "figs/io_boundary.png",
     "caption": "Recall-by-content routes 78% vs word-overlap 70% vs exact-key 0%; solves 78% end to end",
     "bullets": [
         "Readers for JSON and text with checks; a memory store; tool and code writers",
         "The checks catch every bad input we inject and every off-contract output",
         "Every part saves to a file and reloads with no model needed in the loop"]},
    {"type": "figure", "title": "Splitting a budget up a ladder of models (E35)",
     "image": "figs/sprint_ladder.png",
     "caption": "The fixed ceiling rises 15 -> 19/20 with stronger models; the greedy trap fades with scale",
     "bullets": [
         "qwen2.5:7b -> deepseek-r1:14b -> gpt-oss:20b -> qwen3-coder:30b",
         "The greedy trap is a weak-model problem; gpt-oss:20b clears all 20",
         "Which model you use matters far more than the budget strategy"]},
    {"type": "figure", "title": "Snapping pieces gives better understanding (E36)",
     "image": "figs/representations.png",
     "caption": "Every one-big-blob learner collapses on new combos; the piece-by-piece one stays flat",
     "bullets": [
         "The best big blob (gradient boosting) drops from 0.48 to 0.20 by K=5",
         "The collapse happens for every kind of learner we tried",
         "Splitting the problem into pieces -- not scaling the learner -- is what generalizes"]},
    {"type": "figure", "title": "Coping with sudden, silent rule changes (E41)",
     "image": "figs/nonstationary.png",
     "caption": "A code monitor re-finds the rule in 1 step; a sliding window lags, and a frozen one never recovers",
     "bullets": [
         "A system's hidden setting jumps at unannounced times",
         "Because the rule is a clear, nameable program, a few looks re-pin it exactly",
         "This holds as long as the new rule stays in the family we can name"]},
    {"type": "figure", "title": "Agents hopping between linked, changing worlds (E42)",
     "image": "figs/agent_traversal.png",
     "caption": "A per-world monitor scores 0.94 and comebacks cost nothing; one shared learner scores 0.85 and gets confused",
     "bullets": [
         "Two shifting worlds joined by a toll route; the agent hops back and forth",
         "A separate program per world keeps each world's rule safe while it's away",
         "One shared belief can't hold two worlds at the same time"]},
    {"type": "figure", "title": "Next-letter world models: exact even on longer inputs (E45)",
     "image": "figs/next_token.png",
     "caption": "The written program stays exact on new sizes for 3/3 tasks (1.00); the same 30B guessing directly drops to 0.38",
     "bullets": [
         "Parity, dyck, copy: memory a fixed window just can't hold",
         "Writing a program makes it length-proof by design",
         "Both the n-gram and the fixed-window net rot as things get longer"]},
    {"type": "figure", "title": "A database over many worlds at once (E46)",
     "image": "figs/many_worlds.png",
     "caption": "Exact search over 1e18 worlds in 191 ms; the hard-case boundary is shown, not hidden",
     "bullets": [
         "The odds break into pieces -> one small piece per mechanism",
         "One swappable engine answers yes/no, how-many, and how-likely questions",
         "Tie parameters together tightly and that piece blows up as d^w"]},
    {"type": "figure", "title": "Best path through many learning routes (E49)",
     "image": "figs/path_integral.png",
     "caption": "The easiest-path curriculum reuses mastered pieces -- a 6.0x speedup over starting from scratch",
     "bullets": [
         "Weight each route by how easy it is; reuse the E46 engine",
         "A huge number of routes summed cleverly, without listing them all",
         "Different starting roles (engineer, director, CEO) get different best paths"]},
    {"type": "figure", "title": "Safe, tight worst-case bounds (E54)",
     "image": "figs/bounds.png",
     "caption": "The smart bound is 21.5 wide vs a crude 108.6; random sampling is tight but not guaranteed",
     "bullets": [
         "Run the world on whole ranges of states at once -- push the whole set forward",
         "The smart method tracks how errors cancel; the crude one explodes",
         "Gives the world model a worst-case run it can promise to stay inside"]},
    {"type": "figure", "title": "Smart probing to pin down the world (E55)",
     "image": "figs/infogeom.png",
     "caption": "Asking the most informative question finds the true world in 6.5 probes vs 9.4 at random (out of 10)",
     "bullets": [
         "Pick the test whose answer would tell you the most",
         "Be adaptive: stop re-confirming, and separate the worlds still in the running",
         "Because the choices are countable, this is principled experiment design"]},

    {"type": "part", "title": "Stepping back", "subtitle": "Discussion, limits, and what's next"},
    {"type": "bullets", "title": "The big trade, plainly",
     "bullets": [
         "Trained models cover lots of pixels, but pay in piling-up mistakes and being unreadable",
         "Checked code buys exactness, speed, working in new situations, and being inspectable",
         "Inside the plain-facts world, the results all point one way",
         "The workflow: state it, check it with invariants, probe intent, tighten, rebuild",
         "At every stage the thing stays a program you can diff"]},
    {"type": "bullets", "title": "What these worlds unlock: world-time compute",
     "bullets": [
         "Checked worlds label training runs exactly, for free",
         "Training on many worlds of a field lifts skill on worlds it never saw",
         "That's world-time compute -- the topic of the companion paper",
         "Exact, snappable worlds are what make it possible",
         "But a world computer is useful even if you never train on it"]},
    {"type": "bullets", "title": "Values as an open, stated thing",
     "bullets": [
         "Goals are stated out loud -- the good-vs-fair trade-off is a real dial",
         "A weighted sum is just one theory of ethics (adding up consequences)",
         "Roll-ups, hard 'never do this' vetoes, and a moral parliament are different tools",
         "A hard veto can't be faked by any weighting (E25)",
         "Stating values openly handles the values problem step by step; it doesn't solve it"]},
    {"type": "cards", "title": "Where this falls short",
     "cards": [
         {"head": "Scope", "icon": "grid", "text": "Plain-facts worlds only"},
         {"head": "Complexity", "icon": "lock", "text": "One big block breaks past about 8 rules"},
         {"head": "Scale", "icon": "flask", "text": "20 repair tasks, 3 known-answer worlds"},
         {"head": "Trust", "icon": "shield", "text": "The judge is weak; self-check is just a screen"}]},
    {"type": "bullets", "title": "Frozen picture-features can't balance a pole (E67)",
     "bullets": [
         "The picture-guessing kind's best try at balancing a pole still scores 0%",
         "Five ways to attach a controller to frozen V-JEPA-2/DINOv2 all score 0",
         "Yet a simple probe can read the state: it explains 95% of the pole's angle",
         "Strong frozen features are needed but not enough to control",
         "Training end-to-end on the task, not better seeing, closes the gap"]},

    {"type": "section", "title": "Wrapping up"},
    {"type": "statement", "text": "Make the model a program, check the program, and keep the values on dials -- a different road than just piling on parameters until the made-up answers go away."},
    {"type": "bullets", "title": "Takeaways and what's next",
     "bullets": [
         "A no-training plain-code world model is exact where trained rules pile up mistakes",
         "Snapping pieces beats the complexity wall; the limit is measured, not hidden",
         "100 worlds in minutes on a laptop; small, inspectable, shareable files",
         "Next: build worlds by snapping written pieces, standard-size coding, mixing seeing with facts",
         "All the code, 100 recipes, and 79 experiments rebuild from one repository"]},
]
