"""Mine the pre-existing served-observation dataset (fable_nethack/results/transitions,
generated by the source-informed sibling policy - DISCLOSED) as additional
observations for rule evidence. Only served fields are used (action, message,
blstats, done). Output: results/replay_mining.json
"""
import glob
import gzip
import json
import os

BL_TIME, BL_DEPTH, BL_HP = 20, 12, 10  # indices from progress.py (metric def)

out = {"down_depth_plus1": 0, "down_no_change": 0, "down_other": [],
       "depth_change_other_action": [], "frozen_msgs": {}, "n_steps": 0,
       "time_decrease_nonterminal": [], "hp_above_max": 0,
       "single_move_displacement_gt1": 0, "files": 0}

fs = sorted(glob.glob("/data/doh/teams/researchy/work/fable_nethack/results/transitions/*/*.jsonl.gz"))
DIRS = {"north", "south", "east", "west", "northeast", "northwest",
        "southeast", "southwest"}

for path in fs:
    tag = "/".join(path.split("/")[-2:])
    try:
        prev = None
        with gzip.open(path, "rt") as f:
            hdr = json.loads(f.readline())
            step_i = 0
            for line in f:
                r = json.loads(line)
                obs = r.get("obs", {})
                bl = obs.get("blstats")
                if bl is None:
                    continue
                step_i += 1
                out["n_steps"] += 1
                msg = obs.get("message") or ""
                if isinstance(msg, list):
                    msg = bytes(msg).decode("latin-1", "ignore").strip("\x00")
                a = r.get("action")
                done = r.get("done")
                if prev is not None and a is not None:
                    pd, d = prev[BL_DEPTH], bl[BL_DEPTH]
                    pt, t = prev[BL_TIME], bl[BL_TIME]
                    if a == "down":
                        if d == pd + 1:
                            out["down_depth_plus1"] += 1
                        elif d == pd:
                            out["down_no_change"] += 1
                        else:
                            if len(out["down_other"]) < 20:
                                out["down_other"].append([tag, step_i, pd, d, msg[:60]])
                    elif d != pd and not done:
                        if len(out["depth_change_other_action"]) < 40:
                            out["depth_change_other_action"].append(
                                [tag, step_i, a, pd, d, msg[:80]])
                    if t < pt and not done and t != 0:
                        if len(out["time_decrease_nonterminal"]) < 10:
                            out["time_decrease_nonterminal"].append([tag, step_i, pt, t])
                    if bl[BL_HP] > bl[11]:
                        out["hp_above_max"] += 1
                    if a in DIRS and not done:
                        dx = abs(bl[0] - prev[0]); dy = abs(bl[1] - prev[1])
                        if max(dx, dy) > 1 and pd == d:
                            out["single_move_displacement_gt1"] += 1
                if "frozen by" in msg.lower():
                    key = msg.lower().split("frozen by", 1)[1][:30].strip()
                    out["frozen_msgs"][key] = out["frozen_msgs"].get(key, 0) + 1
                prev = bl
        out["files"] += 1
    except Exception as e:
        pass

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "results", "replay_mining.json"), "w") as f:
    json.dump(out, f, indent=1)
print(json.dumps({k: (v if not isinstance(v, list) else v[:5])
                  for k, v in out.items()}, indent=1)[:3000])
