"""CLEAN-protocol agent: consumes ONLY what the benchmark's env returns.

Inputs per step: obs['image'] (7x7x3 egocentric, occluded partial view),
obs['direction'] (compass int), obs['mission'] (language string), and the
episode's reward/termination signals. No env.unwrapped access, no grid
readout, no instruction-tree readout, no clone verification.

(BALROG serves its LLM agents text descriptions generated by gen_graph()
from the *same* gen_obs_grid() partial view, plus the same mission string;
obs['image'] is the array form of that channel.)

Strategy: closed-loop SLAM-then-plan.
  - integrate each view into an allocentric belief map (odometry is exact:
    direction comes from obs, position advances iff the observed front cell
    is traversable)
  - parse the mission into an instruction tree (the same grammar the
    verifier's surface() emits)
  - if the current subgoal's objects are known: plan with the same classical
    planner as the privileged arm, on a belief-state where unknown cells are
    blocked; replan every step
  - else: explore = navigate to face the nearest unknown cell (closed
    unlocked doors may be opened en route; locked doors handled by the
    open-instruction planner itself)
"""

from __future__ import annotations

import re

from symbolic_model import (
    LEFT, RIGHT, FORWARD, PICKUP, DROP, TOGGLE, DIR_TO_VEC,
    IDX_TO_OBJECT, IDX_TO_COLOR, Obj, SymState,
)
from planner import nav_search, PlanFail

COLORS = ["red", "green", "blue", "purple", "yellow", "grey"]
TYPES = ["box", "ball", "key", "door"]


# ------------------------------ mission parsing ------------------------------

def parse_desc(s):
    s = s.strip()
    m = re.fullmatch(r"(?:a|the)\s+(?:(%s)\s+)?(%s)" % ("|".join(COLORS), "|".join(TYPES)), s)
    if not m:
        raise ValueError(f"unparseable desc: {s!r}")
    return {"color": m.group(1), "type": m.group(2)}


def parse_mission(mission: str):
    """Returns an instruction spec tree (dicts)."""
    s = mission.strip()
    m = re.fullmatch(r"(.+), then (.+)", s)
    if m:
        return {"kind": "before", "a": parse_mission(m.group(1)), "b": parse_mission(m.group(2))}
    m = re.fullmatch(r"(.+) after you (.+)", s)
    if m:
        # 'a after you b': b first
        return {"kind": "after", "a": parse_mission(m.group(1)), "b": parse_mission(m.group(2))}
    m = re.fullmatch(r"go to (.+)", s)
    if m:
        return {"kind": "goto", "desc": parse_desc(m.group(1))}
    m = re.fullmatch(r"pick up (.+)", s)
    if m:
        return {"kind": "pickup", "desc": parse_desc(m.group(1))}
    m = re.fullmatch(r"open (.+)", s)
    if m:
        return {"kind": "open", "desc": parse_desc(m.group(1))}
    m = re.fullmatch(r"put (.+) next to (.+)", s)
    if m:
        return {"kind": "putnext", "move": parse_desc(m.group(1)), "fixed": parse_desc(m.group(2))}
    raise ValueError(f"unparseable mission: {mission!r}")


# ------------------------------ belief map ----------------------------------

class Belief:
    def __init__(self):
        self.cells = {}      # (x, y) -> None (empty) | (type, color, state)
        self.pos = (0, 0)
        self.dir = 0
        self.carrying = None  # (type, color) | None
        # position the currently-carried object was picked from (for the
        # verifier's stale-obj_poss semantics: GoTo positions refresh only
        # on DROP, so the pickup cell remains a valid GoTo target)
        self.carried_from = None

    def integrate(self, obs):
        """Fuse the 7x7 egocentric view into the map. Inverse of the env's
        slice+rotate pipeline (validated: render_view == obs image)."""
        img = obs["image"]
        self.dir = int(obs["direction"])
        n = 7
        # In the view frame the agent is at (n//2, n-1) facing 'up' (-vy).
        # World basis: forward f = DIR_TO_VEC[dir], right r = (-f[1], f[0])
        fx, fy = DIR_TO_VEC[self.dir]
        rx, ry = -fy, fx
        ax, ay = self.pos
        for vx in range(n):
            for vy in range(n):
                t, c, st = (int(img[vx][vy][0]), int(img[vx][vy][1]), int(img[vx][vy][2]))
                if t == 0:      # unseen
                    continue
                dv_right = vx - n // 2
                dv_fwd = (n - 1) - vy
                wx = ax + fx * dv_fwd + rx * dv_right
                wy = ay + fy * dv_fwd + ry * dv_right
                if (vx, vy) == (n // 2, n - 1):
                    # agent cell shows carried object, not the floor
                    self.carrying = None if t == 1 else (IDX_TO_OBJECT[t], IDX_TO_COLOR[c])
                    continue
                self.cells[(wx, wy)] = None if t == 1 else (IDX_TO_OBJECT[t], IDX_TO_COLOR[c], st)

    def predict(self, action):
        """Advance odometry + local map for our own action (exact: front cell
        is always in view)."""
        f = (self.pos[0] + DIR_TO_VEC[self.dir][0], self.pos[1] + DIR_TO_VEC[self.dir][1])
        front = self.cells.get(f, "unknown")
        if action == FORWARD:
            traversable = front is None or (
                front != "unknown" and front is not None
                and front[0] == "door" and front[2] == 0)
            if traversable:
                self.pos = f
        elif action == PICKUP:
            if (front not in (None, "unknown")
                    and front[0] in ("key", "ball", "box") and self.carrying is None):
                self.carried_from = f
                # cell becomes empty; carrying will be confirmed by next obs
                self.cells[f] = None
        elif action == DROP:
            if front is None and self.carrying is not None:
                self.cells[f] = (self.carrying[0], self.carrying[1], 0)
                self.carried_from = None
        # LEFT/RIGHT/TOGGLE effects come back through the next observation
        # (dir from obs; door state changes are re-observed since the door
        # is in front of us).

    # ---- planner interface: build a blocked-unknown SymState ----
    def to_state(self):
        """SymState over the belief bounding box; unknown cells inside the
        box become blocking pseudo-walls with oid -1."""
        if not self.cells:
            return None, set()
        xs = [p[0] for p in self.cells] + [self.pos[0]]
        ys = [p[1] for p in self.cells] + [self.pos[1]]
        x0, x1 = min(xs), max(xs)
        y0, y1 = min(ys), max(ys)
        w, h = x1 - x0 + 1, y1 - y0 + 1
        st = SymState(w, h, 10 ** 9)
        unknown = set()
        oid = 0
        for x in range(x0, x1 + 1):
            for y in range(y0, y1 + 1):
                p = (x - x0, y - y0)
                v = self.cells.get((x, y), "unknown")
                if v == "unknown":
                    st.grid[p] = -1000 - len(unknown)
                    st.objs[st.grid[p]] = Obj(st.grid[p], "wall", "grey")
                    unknown.add(p)
                elif v is not None:
                    t, c, s = v
                    st.grid[p] = oid
                    st.objs[oid] = Obj(oid, t, c, is_open=(t == "door" and s == 0),
                                       is_locked=(t == "door" and s == 2))
                    oid += 1
        st.agent_pos = (self.pos[0] - x0, self.pos[1] - y0)
        st.agent_dir = self.dir
        if self.carrying is not None:
            st.carrying = 9999
            st.objs[9999] = Obj(9999, self.carrying[0], self.carrying[1])
        return (st, unknown, (x0, y0))


# ------------------------------ the agent -----------------------------------

class CleanAgent:
    def __init__(self, mission):
        self.spec = parse_mission(mission)
        self.belief = Belief()
        self.phase_done = False   # for seq instructions: first sub-instr done

    # -- helpers over belief-state --
    @staticmethod
    def _matches(obj, desc):
        return (obj.type == desc["type"]
                and (desc["color"] is None or obj.color == desc["color"]))

    def _known_positions(self, st, desc, exclude_carried_from=False):
        out = [p for p, o in st.grid.items()
               if o >= 0 and self._matches(st.objs[o], desc)]
        return out

    def act(self, obs):
        """Return the next action (int)."""
        b = self.belief
        b.integrate(obs)
        pack = b.to_state()
        if pack is None:
            return LEFT
        st, unknown, (x0, y0) = pack

        spec = self.spec
        if spec["kind"] in ("before", "after"):
            first = spec["a"] if spec["kind"] == "before" else spec["b"]
            second = spec["b"] if spec["kind"] == "before" else spec["a"]
            # first is always 'pick up X' in this suite; done iff carrying X
            if not self.phase_done:
                if b.carrying is not None and self._matches(
                        Obj(0, b.carrying[0], b.carrying[1]), first["desc"]):
                    self.phase_done = True
            cur = second if self.phase_done else first
        else:
            cur = spec

        a = self._act_for(cur, st, unknown, x0, y0)
        b.predict(a)
        return a

    def _act_for(self, cur, st, unknown, x0, y0):
        kind = cur["kind"]
        try:
            if kind == "goto":
                targets = self._known_positions(st, cur["desc"])
                # stale-position semantics: the pickup cell of the object we
                # carry counts until a drop refreshes obj_poss
                if (self.belief.carried_from is not None
                        and self.belief.carrying is not None
                        and self._matches(Obj(0, *self.belief.carrying), cur["desc"])):
                    cf = (self.belief.carried_from[0] - x0,
                          self.belief.carried_from[1] - y0)
                    targets.append(cf)
                if targets:
                    return self._nav_face_or_hold(st, targets)
            elif kind == "pickup":
                if self.belief.carrying is None:
                    targets = self._known_positions(st, cur["desc"])
                    if targets:
                        acts = self._nav_face(st, targets)
                        return acts[0] if acts else PICKUP
                else:
                    return self._drop_somewhere(st)
            elif kind == "open":
                doors = [(p, st.objs[st.grid[p]]) for p in
                         self._known_positions(st, cur["desc"])]
                if doors:
                    return self._open_door_action(st, doors)
            elif kind == "putnext":
                a = self._putnext_action(st, cur)
                if a is not None:
                    return a
        except PlanFail:
            pass
        # fall through: explore
        return self._explore(st, unknown)

    # -- concrete sub-planners (first-action of a replanned-every-step plan) --

    def _nav_face(self, st, targets):
        tset = set(targets)

        def goal(pos, d):
            f = (pos[0] + DIR_TO_VEC[d][0], pos[1] + DIR_TO_VEC[d][1])
            return f in tset

        acts, _ = nav_search(st, [(st.agent_pos, st.agent_dir, 0)], goal)
        return acts

    def _nav_face_or_hold(self, st, targets):
        acts = self._nav_face(st, targets)
        # empty plan = already facing the target; PICKUP preserves front_pos
        # and cannot invalidate the verifier's (stale) position list
        return acts[0] if acts else PICKUP

    def _drop_somewhere(self, st):
        def goal(pos, d):
            f = (pos[0] + DIR_TO_VEC[d][0], pos[1] + DIR_TO_VEC[d][1])
            return (0 <= f[0] < st.width and 0 <= f[1] < st.height
                    and st.obj_at(f) is None)
        acts, _ = nav_search(st, [(st.agent_pos, st.agent_dir, 0)], goal)
        return acts[0] if acts else DROP

    def _open_door_action(self, st, doors):
        # prefer already-satisfiable doors; handle locked via key
        best = None
        for pos, door in doors:
            if door.is_locked:
                car = self.belief.carrying
                if car is not None and car == ("key", door.color):
                    acts = self._nav_face(st, [pos])
                    cand = acts[0] if acts else TOGGLE
                elif car is not None:
                    cand = self._drop_somewhere(st)
                else:
                    keys = [p for p, o in st.grid.items()
                            if o >= 0 and st.objs[o].type == "key"
                            and st.objs[o].color == door.color]
                    if not keys:
                        raise PlanFail("need key, none known")
                    acts = self._nav_face(st, keys)
                    cand = acts[0] if acts else PICKUP
            elif door.is_open:
                # toggle twice while facing it; closed-then-open
                acts = self._nav_face(st, [pos])
                cand = acts[0] if acts else TOGGLE
            else:
                acts = self._nav_face(st, [pos])
                cand = acts[0] if acts else TOGGLE
            if best is None:
                best = cand
        if best is None:
            raise PlanFail("no doors")
        return best

    def _putnext_action(self, st, cur):
        b = self.belief
        move_known = self._known_positions(st, cur["move"])
        fixed_known = self._known_positions(st, cur["fixed"])
        carrying_move = (b.carrying is not None
                         and self._matches(Obj(0, *b.carrying), cur["move"]))
        if carrying_move:
            if not fixed_known:
                return None  # explore for the fixed object
            drop_cells = set()
            for fp in fixed_known:
                for dx, dy in DIR_TO_VEC:
                    c = (fp[0] + dx, fp[1] + dy)
                    if (0 <= c[0] < st.width and 0 <= c[1] < st.height
                            and st.obj_at(c) is None):
                        drop_cells.add(c)
            if not drop_cells:
                raise PlanFail("no drop cell")
            acts = self._nav_face(st, drop_cells)
            return acts[0] if acts else DROP
        if b.carrying is not None:
            return self._drop_somewhere(st)
        if move_known and fixed_known:
            acts = self._nav_face(st, move_known)
            return acts[0] if acts else PICKUP
        if move_known and not fixed_known:
            return None  # find the fixed object first (avoids carrying blind)
        return None

    def _explore(self, st, unknown):
        if unknown:
            def goal(pos, d):
                f = (pos[0] + DIR_TO_VEC[d][0], pos[1] + DIR_TO_VEC[d][1])
                return f in unknown
            try:
                acts, _ = nav_search(st, [(st.agent_pos, st.agent_dir, 0)], goal)
                if acts:
                    return acts[0]
            except PlanFail:
                pass
        # unknown region unreachable through known-free space: try doors
        # (closed unlocked doors are handled inside nav; locked doors need
        # the key - grab a matching key if we see one)
        for p, o in st.grid.items():
            obj = st.objs[o]
            if o >= 0 and obj.type == "door" and obj.is_locked:
                if self.belief.carrying == ("key", obj.color):
                    acts = self._nav_face(st, [p])
                    return acts[0] if acts else TOGGLE
                if self.belief.carrying is None:
                    keys = [q for q, k in st.grid.items()
                            if k >= 0 and st.objs[k].type == "key"
                            and st.objs[k].color == obj.color]
                    if keys:
                        acts = self._nav_face(st, keys)
                        return acts[0] if acts else PICKUP
        return LEFT  # last resort: spin to look around
