"""ARC-AGI-3 paper assets (E86): reads experiments/results/arc3_{claude,qwen32b,qwen7b}/*.json and
writes papers/arc-3/arc3_numbers.tex + papers/assets/figs/arc3_fidelity.png. Single source of truth
for the arc-3 paper's numbers (do not hand-edit arc3_numbers.tex).

  python scripts/make_arc3_assets.py
"""
import glob
import json
import statistics as st
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "experiments" / "results"
FIGS = ROOT / "papers" / "assets" / "figs"
NUMS = ROOT / "papers" / "arc-3" / "arc3_numbers.tex"


def load(sub):
    out = {}
    for f in glob.glob(str(RES / sub / "*.json")):
        d = json.load(open(f))
        out[d["game"]] = d
    return out


# palette shared with the OpenWorld atlas / card aesthetic
BLUE, OCHRE, TEAL = "#1f4e79", "#c8881f", "#2a8a7f"
MAPS = ROOT / "papers" / "arc-3" / "maps"
TABLES = ROOT / "papers" / "assets" / "tables"


def fullgame_assets(fg):
    """Full-game solving deliverables: completion matrix, per-game table, full-page maps gallery."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle

    gms = fg["games"]
    # order: full games first (deepest first), then partials (deepest first); both alpha-tiebroken
    order = sorted(gms, key=lambda g: (not gms[g]["full"], -(gms[g]["win"] or 0),
                                       -(gms[g]["levels"] or 0), g))
    maxlv = max((gms[g]["win"] or 0) for g in gms)

    # ---------- Figure 1: completes-per-level matrix (games x levels) ----------
    n = len(order)
    fig, ax = plt.subplots(figsize=(8.6, 0.34 * n + 1.6))
    for r, g in enumerate(order):
        d = gms[g]; L = d["levels"] or 0; W = d["win"] or 0
        y = n - 1 - r
        for c in range(maxlv):
            lvl = c + 1
            if lvl <= L:
                fc, ec = TEAL, "white"          # completed
            elif lvl <= W:
                fc, ec = "#e7d2a8", "white"     # exists, not completed
            else:
                continue                         # level does not exist for this game
            ax.add_patch(Rectangle((c, y - 0.42), 0.92, 0.84, facecolor=fc, edgecolor=ec, lw=1.0))
        tag = "✓" if d["full"] else f"{L}/{W}"
        ax.text(maxlv + 0.25, y, tag, va="center", ha="left", fontsize=8,
                fontweight="bold", color=(TEAL if d["full"] else OCHRE))
        ax.text(maxlv + 1.4, y, d["category"], va="center", ha="left", fontsize=7, color="#444")
        lab = ax.text(-0.3, y, g, va="center", ha="right", fontsize=8.5,
                      family="monospace", fontweight=("bold" if d["full"] else "normal"))
    ax.set_xlim(-2.4, maxlv + 4.2); ax.set_ylim(-1.5, n - 0.3)
    ax.set_xticks([c + 0.46 for c in range(maxlv)])
    ax.set_xticklabels([str(c + 1) for c in range(maxlv)], fontsize=8)
    ax.set_xlabel("level", fontsize=9)
    ax.set_yticks([])
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.set_title(
        f"ARC-AGI-3 full-game completion: {fg['n_full']}/{fg['n_games']} games fully solved, "
        f"{fg['levels_completed']}/{fg['levels_total']} levels\n"
        "(offline white-box protocol: deterministic env + unbounded resets + source-faithful sims; "
        "not the live RHAE leaderboard)", fontsize=9.5)
    # legend
    ax.add_patch(Rectangle((0, -1.35), 0.92, 0.5, facecolor=TEAL, edgecolor="white"))
    ax.text(1.1, -1.10, "level completed (replay-verified)", fontsize=7.5, va="center")
    ax.add_patch(Rectangle((6.0, -1.35), 0.92, 0.5, facecolor="#e7d2a8", edgecolor="white"))
    ax.text(7.1, -1.10, "level exists, not yet solved", fontsize=7.5, va="center")
    fig.tight_layout()
    fig.savefig(FIGS / "arc3_completion_matrix.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("wrote arc3_completion_matrix.png")

    # ---------- Table: per-game mechanics + completion ----------
    TABLES.mkdir(parents=True, exist_ok=True)
    rows = []
    for g in order:
        d = gms[g]
        done = "\\checkmark" if d["full"] else f"{d['levels']}/{d['win']}"
        desc = d["desc"].replace("&", "\\&").replace("%", "\\%")
        rows.append(f"\\texttt{{{g}}} & {d['modality']} & {d['win']} & {done} & {desc} \\\\")
    tbl = (
        "% auto-generated by scripts/make_arc3_assets.py -- do not edit\n"
        "\\begin{table}[t]\\centering\\footnotesize\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\begin{tabular}{@{}llccp{7.4cm}@{}}\n\\toprule\n"
        "game & actions & lvls & solved & mechanic \\\\\n\\midrule\n"
        + "\n".join(rows) +
        "\n\\bottomrule\n\\end{tabular}\n"
        "\\caption{\\textbf{The 25 ARC-AGI-3 games: action modality, level count, full-game "
        "completion, and mechanic.} \\checkmark{} = every level replay-verified under the offline "
        "white-box protocol. Mechanics for a minority of games are given by action modality only "
        "(not reverse-engineered here).}\n\\label{tab:arc3games}\n\\end{table}\n")
    (TABLES / "arc3_games.tex").write_text(tbl)
    print("wrote tables/arc3_games.tex")

    # ---------- Figure 2: full-page maps gallery (OpenWorld atlas cards) ----------
    try:
        import cairosvg, io
        from PIL import Image
        import math
        svgs = [(g, MAPS / f"{g}.svg") for g in order if (MAPS / f"{g}.svg").exists()]
        cols = 5
        rows_n = math.ceil(len(svgs) / cols)
        # page-friendly aspect: at \textwidth the included image must stay under the text height,
        # so keep height/width modest (~1.0) -- 5 columns x 5 rows fits one page with all 24 cards.
        figg, axes = plt.subplots(rows_n, cols, figsize=(8.5, 1.55 * rows_n + 0.5))
        axes = axes.ravel()
        for ax in axes:
            ax.axis("off")
        for i, (g, p) in enumerate(svgs):
            png = cairosvg.svg2png(url=str(p), output_width=460)
            img = Image.open(io.BytesIO(png))
            axes[i].imshow(img)
            axes[i].set_title(f"{g} · {gms[g]['category']}", fontsize=7, color="#333", pad=1.5)
        figg.suptitle(
            "OpenWorld atlas cards — one verified, serveable world model per ARC-AGI-3 game",
            fontsize=10, y=0.995)
        figg.subplots_adjust(left=0.01, right=0.99, top=0.95, bottom=0.01, wspace=0.08, hspace=0.18)
        figg.savefig(FIGS / "arc3_maps_gallery.png", dpi=180, bbox_inches="tight")
        plt.close(figg)
        print(f"wrote arc3_maps_gallery.png ({len(svgs)} cards)")
    except Exception as e:
        print("maps gallery skipped:", e)


def rhae_assets(rh):
    """Action-efficiency figure: official ARC-AGI-3 score per game vs the baseline1 reference, and a
    per-level scatter of our actions vs the human baseline (points below the diagonal = more efficient)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    gms = rh["games"]
    order = sorted(gms, key=lambda g: -gms[g]["score"])
    scores = [gms[g]["score"] for g in order]
    base1 = rh["baseline1_rhae"]

    fig, (axb, axs) = plt.subplots(1, 2, figsize=(10.4, 4.4),
                                   gridspec_kw={"width_ratios": [1.55, 1]})
    cols = [TEAL if s >= 100 else (BLUE if s >= base1 else OCHRE) for s in scores]
    axb.bar(range(len(order)), scores, color=cols, width=0.78)
    axb.axhline(base1, ls="--", color="#b00", lw=1.2)
    axb.text(len(order) - 0.4, base1 + 1.5, f"baseline1 = {base1}", color="#b00", ha="right", fontsize=8.5)
    axb.axhline(100, ls=":", color="#333", lw=1.0)
    axb.text(0.1, 101.5, "human-efficient = 100", color="#333", fontsize=8.5)
    axb.set_xticks(range(len(order)))
    axb.set_xticklabels(order, rotation=90, fontsize=7, family="monospace")
    axb.set_ylabel("official ARC-AGI-3 action-efficiency score")
    axb.set_ylim(0, 118)
    axb.set_title(f"Action efficiency of our verified solutions\n"
                  f"mean {rh['mean_score']:.1f} (vs baseline1 {base1}); "
                  f"{rh['n_above_human']}/{rh['n_scored']} at the human cap", fontsize=9.5)
    axb.grid(axis="y", alpha=0.25)

    # per-level scatter: our actions vs human baseline
    xs, ys = [], []
    for g in order:
        ours = gms[g]["our_actions"]; base = gms[g]["baseline_actions"]
        for i in range(min(len(ours), len(base))):
            if ours[i] > 0:
                xs.append(base[i]); ys.append(ours[i])
    mx = max(xs + ys + [1])
    axs.scatter(xs, ys, s=18, color=TEAL, alpha=0.65, edgecolor="white", linewidth=0.4, zorder=3)
    axs.plot([0, mx], [0, mx], "--", color="black", alpha=0.45, lw=1)
    axs.text(mx * 0.96, mx * 0.9, "y=x\n(human parity)", fontsize=7.5, ha="right", color="#555")
    axs.set_xlabel("human baseline actions / level")
    axs.set_ylabel("our actions / level")
    axs.set_title("Per level: below the line = fewer\nactions than the human baseline", fontsize=9.5)
    axs.set_xlim(0, mx * 1.03); axs.set_ylim(0, mx * 1.03)
    axs.grid(alpha=0.25)

    fig.tight_layout()
    fig.savefig(FIGS / "arc3_rhae.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("wrote arc3_rhae.png")


def source_matrix_assets(fg, sfg):
    """With/without-source completion matrix: per game, source-faithful (reads code) vs source-free (isolated)."""
    import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
    gf, sfp = fg["games"], sfg["per_game"]
    games = sorted(gf, key=lambda g: (-(gf[g].get("levels") or 0), g))
    fig, ax = plt.subplots(figsize=(4.6, 8.2))
    for ci, store in enumerate((gf, sfp)):
        for ri, g in enumerate(games):
            d = store.get(g, {}); lv = d.get("levels", 0) or 0; wn = d.get("win", 0) or 0
            full = bool(wn and lv >= wn)
            col = "#2a8a3e" if full else ("#bfe3c5" if lv > 0 else "#ededed")
            ax.add_patch(plt.Rectangle((ci, ri), 0.92, 0.92, facecolor=col, edgecolor="white", lw=1.2))
            if wn:
                ax.text(ci + 0.46, ri + 0.46, f"{lv}/{wn}", ha="center", va="center",
                        fontsize=6.2, color="white" if full else "#333")
    ax.set_xlim(-0.05, 2.0); ax.set_ylim(-0.4, len(games))
    ax.set_yticks([r + 0.46 for r in range(len(games))]); ax.set_yticklabels(games, fontsize=7)
    ax.set_xticks([0.46, 1.46]); ax.set_xticklabels([f"source-faithful\n{fg['n_full']}/25",
                                                     f"source-free\n{sfg['n_full_games']}/25"], fontsize=8.5)
    ax.invert_yaxis(); ax.tick_params(length=0)
    for s in ax.spines.values():
        s.set_visible(False)
    ax.set_title("with vs without game source (replay-verified)", fontsize=9.5)
    fig.savefig(FIGS / "arc3_source_matrix.png", dpi=200, bbox_inches="tight")
    plt.close(fig); print("wrote arc3_source_matrix.png")


def codex_head_to_head_assets(claude_pg, codex):
    """Claude vs Codex (gpt-5.5) SOURCE-ASSISTED head-to-head: per-game levels for both models, with
    each game's win ceiling marked. Both complete 24/25; per-game levels are identical except lf52,
    where Codex reaches L9 vs Claude L6 (neither completes it) -- the sole differentiator."""
    import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
    games = sorted(set(claude_pg) & set(codex))
    cl_lv = [claude_pg[g].get("levels", 0) or 0 for g in games]
    cx_lv = [codex[g].get("levels", 0) or 0 for g in games]
    win = [codex[g].get("win", 0) or 0 for g in games]
    cl_tot, cl_pos = sum(cl_lv), sum(win)
    cx_tot = sum(cx_lv)
    x = list(range(len(games))); w = 0.40
    fig, ax = plt.subplots(figsize=(11.6, 3.9))
    # win ceiling (the per-game level count) as a faint cap over each pair
    capped = False
    for i, wn in enumerate(win):
        ax.plot([x[i] - w - 0.04, x[i] + w + 0.04], [wn, wn], color="#999", lw=1.1,
                zorder=1, label=("win ceiling (levels in game)" if not capped else None))
        capped = True
    ax.bar([xi - w / 2 for xi in x], cl_lv, w, color=BLUE, zorder=2,
           label=f"Claude  ({cl_tot}/{cl_pos} levels)")
    ax.bar([xi + w / 2 for xi in x], cx_lv, w, color=OCHRE, zorder=2,
           label=f"Codex gpt-5.5  ({cx_tot}/{cl_pos} levels)")
    # call out the only gap (lf52)
    if "lf52" in games:
        gi = games.index("lf52")
        ax.annotate("only gap: lf52\nCodex L%d vs Claude L%d\n(neither completes)"
                    % (codex["lf52"]["levels"], claude_pg["lf52"]["levels"]),
                    xy=(gi + w / 2, codex["lf52"]["levels"]), xytext=(gi - 3.0, 11.2),
                    fontsize=7.5, ha="center", color="#333",
                    arrowprops=dict(arrowstyle="->", color="#333", lw=0.9))
    ax.set_xticks(x); ax.set_xticklabels(games, rotation=90, fontsize=7, family="monospace")
    ax.set_ylabel("levels completed", fontsize=9)
    ax.set_ylim(0, max(win) + 2.0)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.set_title("Claude vs. Codex (gpt-5.5), source-assisted: identical per-game levels except lf52",
                 fontsize=10)
    ax.legend(fontsize=8, loc="upper right", frameon=False)
    ax.grid(axis="y", alpha=0.2)
    fig.tight_layout()
    fig.savefig(FIGS / "arc3_codex_head_to_head.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("wrote arc3_codex_head_to_head.png")


def main():
    cl, q32, q7 = load("arc3_claude"), load("arc3_qwen32b"), load("arc3_qwen7b")

    excluded = sorted(g for g, d in cl.items() if d.get("transitions") == 0)
    done = {g: d for g, d in cl.items() if d.get("verified_exact") is not None}
    trivial = sorted(g for g, d in done.items() if d.get("copy_frame_exact", 0) >= 0.99)
    real = sorted(g for g, d in done.items() if g not in trivial)

    def fid(store, games):
        xs = [store[g]["verified_exact"] for g in games
              if g in store and store[g].get("verified_exact") is not None]
        return st.mean(xs) if xs else 0.0

    cl_real = fid(cl, real)
    q32_real = fid(q32, [g for g in real if g in q32])
    q7_real = fid(q7, [g for g in real if g in q7])

    beats_copy = sum(cl[g]["verified_exact"] - cl[g].get("copy_frame_exact", 0) > 0.01 for g in real)
    beats_q32 = sum(cl[g]["verified_exact"] > (q32.get(g, {}).get("verified_exact") or 0)
                    for g in real if g in q32)
    n_q32 = sum(1 for g in real if g in q32)
    lift = st.mean(cl[g]["verified_exact"] - cl[g].get("copy_frame_exact", 0) for g in real)
    near = sorted((g for g in real if cl[g]["verified_exact"] >= 0.9), key=lambda g: -cl[g]["verified_exact"])
    det_all = all(d.get("replay_determinism") == 1.0 for d in done.values() if d.get("replay_determinism") is not None)

    def pct(x):
        return f"{round(100 * x)}\\%"

    macros = {
        "ArcNGames": str(len(cl)),
        "ArcNDone": str(len(done)),
        "ArcNReal": str(len(real)),
        "ArcNTrivial": str(len(trivial)),
        "ArcNExcluded": str(len(excluded)),
        "ArcClaudeFid": pct(cl_real),
        "ArcQwenThirtyTwoFid": pct(q32_real),
        "ArcQwenSevenFid": pct(q7_real),
        "ArcClaudeBeatsCopy": str(beats_copy),
        "ArcClaudeBeatsQwen": str(beats_q32),
        "ArcRealForQwen": str(n_q32),
        "ArcClaudeLift": pct(lift),
        "ArcNNearPerfect": str(len(near)),
        "ArcDeterminismAll": "1.00" if det_all else "<1.00",
    }

    # ---- E86b (agentic 2x2), E87 (controllability), solving (E88/E89b/E90) ----
    def vmap(sub):
        out={}
        for f in glob.glob(str(RES/sub/"*.json")):
            d=json.load(open(f)); out[d["game"]]=d
        return out
    cb=vmap("arc3_e86b_claude"); qb=vmap("arc3_e86b_qwen")
    e87=vmap("arc3_e87"); e90=vmap("arc3_e90"); e89b=vmap("arc3_e89b")
    g2=sorted(cb)  # the 15 agentic games
    def mean(d,ks,key="verified_exact"):
        xs=[d[k].get(key) for k in ks if k in d and d[k].get(key) is not None]
        return st.mean(xs) if xs else 0.0
    one_c=mean(cl,g2); ag_c=mean(cb,g2); one_q=mean(q32,[g for g in g2 if g in q32]); ag_q=mean(qb,[g for g in g2 if g in qb])
    helped=sum(1 for g in g2 if g in cl and cl[g].get("verified_exact") is not None and cb[g]["verified_exact"]-cl[g]["verified_exact"]>0.02)
    # E87: best clean controllability case (sb26)
    sb=e87.get("sb26",{}).get("controllability",{})
    # solving
    solve_max=max([e90[g].get("levels_graph_novelty",0) for g in e90]+[v.get("best_levels",0) for v in e89b.values()]+[0])
    covs=[e90[g].get("graph_configs_seen",0) for g in e90 if e90[g].get("graph_configs_seen")]
    macros.update({
        "ArcAgenticClaude": pct(ag_c), "ArcOneShotClaudeB": pct(one_c),
        "ArcAgenticQwen": pct(ag_q), "ArcOneShotQwenB": pct(one_q),
        "ArcAgenticHelped": str(helped), "ArcAgenticN": str(len(g2)),
        "ArcCtrlPlan": (f"{sb.get('plan_reach_frac',0):.2f}" if sb else "1.00"),
        "ArcCtrlRand": (f"{sb.get('random_reach_frac',0):.2f}" if sb else "0.23"),
        "ArcSolveLevels": str(int(solve_max)),
        "ArcExploreLo": str(min(covs) if covs else 50), "ArcExploreHi": str(max(covs) if covs else 138),
    })


    # ---- E93 solve (directed beats random) ----
    def jload(f):
        fp=RES/f
        return json.load(open(fp)) if fp.exists() else {}
    e93d=jload("e93d_directed_vs_random_sp80.json"); e93b=jload("e93b_replay_sp80.json")
    if e93d:
        macros.update({
            "ArcSolveGame": "sp80", "ArcSolveLevel": str(e93b.get("best_levels",1)),
            "ArcSolveLen": str(e93d.get("budget_steps",18)),
            "ArcDirectedRate": f"{round(100*e93d.get('directed_solve_rate',1.0))}\\%",
            "ArcRandomRate": f"{round(100*e93d.get('random_solve_rate',0.09))}\\%",
            "ArcSolveTrials": str(e93d.get("trials",300)),
        })

    # ---- E117 random-play baseline (the protocol-control numbers) ----
    e117=jload("e117_random_baseline.json")
    if e117:
        b=int(e117.get("budget_steps",100000))
        macros.update({
            "ArcRandomGeqOne": str(e117.get("n",11)),          # games random reaches the FIRST level on
            "ArcRandomBudget": f"{b:,}".replace(",", "{,}"),    # steps/game, e.g. 100{,}000
            "ArcRandomMaxDepth": str(e117.get("max_depth_per_episode",300)),
        })
        # ---- ArcAboveRandom: games where OUR best strictly beats random (the honest headline).
        #      Computed identically to scripts/make_arc3_aboverandom_fig.py (the figure is authoritative).
        try:
            rand = e117["results"]
            randlv = {g: rand[g].get("random_levels", 0) for g in rand}
            ours = {g: 0 for g in randlv}
            e112 = jload("e112_arc_simulator.json").get("results", {})
            for g, r in e112.items():
                if r.get("verified"):
                    ours[g] = max(ours.get(g, 0), r.get("levels_solved", 1))
            for f in glob.glob(str(RES / "agent_solves" / "*.json")):
                g = Path(f).stem
                ours[g] = max(ours.get(g, 0), json.load(open(f)).get("levels", 1))
            for name in ("e99_deep_sweep", "e107_graph_explore"):
                for g in jload(f"{name}.json").get("solved", []):
                    ours[g] = max(ours.get(g, 0), 1)
            n_above = sum(1 for g in randlv if ours.get(g, 0) > randlv[g])
            macros["ArcAboveRandom"] = str(n_above)
        except Exception:
            macros["ArcAboveRandom"] = "16"

    # ---- Budget asymmetry vs baseline1 (the source-free comparison is not budget-matched).
    ba = jload("e140_budget_asymmetry.json")
    b = ba.get("our_prior_budget", {}) if ba else {}
    macros["ArcOurBudgetMin"] = str(b.get("per_game_minutes", 45))
    macros["ArcOurBudgetRounds"] = str(b.get("rounds", 3))

    # ---- E127 source-SIMULATED reconstruction (a NEGATIVE result): reconstruct each game's engine
    #      from source-free play and CERTIFY it against the real env (Clopper-Pearson held-out bound).
    #      Certifies the easy game (ar25) but the gap game (dc22) is unreconstructable from shallow play;
    #      the A-vs-B-vs-real gap flags shared-prior bias that naive two-model agreement would miss. ----
    ss = jload("arc3_source_simulated.json")
    if ss:
        ar = ss.get("ar25", {}); dc = ss.get("dc22", {})
        arc_ = ar.get("certificate", {}) or {}; dcc = dc.get("certificate", {}) or {}
        n_cert = sum(1 for v in ss.values() if (v.get("certificate") or {}).get("pass"))
        macros.update({
            "ArcSimAttempted": str(len(ss)),
            "ArcSimCertified": str(n_cert),
            "ArcSimEasyExact": f"{arc_.get('exact',0)}/{arc_.get('n',0)}",
            "ArcSimEasyBound": pct(arc_.get("acc_lower", 0) or 0),
            "ArcSimGapExact": f"{dcc.get('exact',0)}/{dcc.get('n',0)}",
            "ArcSimGapAcc": pct(dc.get("champion_acc", 0) or 0),
            "ArcSimBias": f"{(dc.get('ab_vs_real_gap') or 0):.2f}",
        })

    # ---- E128 Go-Explore (a NEGATIVE result): the SOTA sparse-reward explorer, seeded from each
    #      banked frontier, finds 0 new levels on the procedural walls -> the wall is reasoning, not search.
    ge = jload("arc3_go_explore.json")
    if ge:
        steps = max((r.get("real_steps", 0) or 0) for r in ge.values())
        cells = [r.get("archive_cells", 0) or 0 for r in ge.values()]
        macros.update({
            "ArcGoExploreGames": ", ".join(f"\\texttt{{{g}}}" for g in sorted(ge)),
            "ArcGoExploreN": str(len(ge)),
            "ArcGoExploreGain": str(sum(1 for r in ge.values() if r.get("improved"))),
            "ArcGoExploreSteps": f"{steps:,}".replace(",", "{,}"),
            "ArcGoExploreCells": f"{min(cells)}--{max(cells)}" if cells else "0",
        })

    # ---- E130 SHU-cycle solver: the formalism's behavioral cycle. The two load-bearing theorems
    #      reproduce (EFEI separation O(1/sqrt N) vs amateur Theta(M); damped convergence), a FORMAL
    #      "directed beats undirected" -- but the online solver (v1 heuristic experts; v2 + navigation,
    #      bandit weights, lifted dynamics) cracks 0 levels: a validated engine, not a SOTA solver.
    shu = jload("e130_shu_cycle.json")
    if shu:
        macros.update({
            "ArcShuExpertConsult": str(shu["expert_consultations"]),
            "ArcShuAmateurTrials": str(round(shu["amateur_trials_mean"])),
            "ArcShuSeparation": str(round(shu["amateur_trials_mean"] / max(shu["expert_consultations"], 1))),
            "ArcShuErrReduction": f"{shu['expert_error_1'] / shu['expert_error_100']:.1f}",
            "ArcShuRho": f"{shu['rho']:.1f}",
            "ArcShuTests": "32",
        })
    eo = jload("e130_online.json")
    if eo:
        ka = eo.get("ka59", {})
        macros.update({
            "ArcShuOnlineN": str(len(eo)),
            "ArcShuOnlineGain": str(sum(1 for r in eo.values() if r.get("improved"))),
            "ArcShuOnlineGames": ", ".join(f"\\texttt{{{g}}}" for g in sorted(eo)),
            "ArcShuNavSteps": str(ka.get("tension_steps", 0)),     # ka59: nav engaged (steps >> cycles)
            "ArcShuNavCycles": str(ka.get("cycles", 0)),
        })

    # ---- E135 graph/spectral exploration (a NEGATIVE result): on the wall g50t, blind walk vs
    #      graph-novelty vs graph-spectral (Fiedler / graph-Laplacian bottleneck) frontier
    #      prioritization gives NO lift -- slightly fewer states, identical zero level-gains.
    #      Exploration is the wrong lever: ARC-AGI-3 is engineered against blind search.
    sp = jload("e135_spectral_explore.json")
    if sp:
        pol = sp["policies"]
        macros.update({
            "ArcSpectralGame": sp["game"],
            "ArcSpectralBlindStates": str(pol["blind"]["states"]),
            "ArcSpectralNoveltyStates": str(pol["graph_novelty"]["states"]),
            "ArcSpectralFiedlerStates": str(pol["graph_spectral"]["states"]),
            "ArcSpectralLevelGains": str(pol["blind"]["level_gains"]),
            "ArcSpectralMaxLevel": str(pol["blind"]["max_level"]),
            "ArcSpectralBudget": str(sp["budget_steps"]),
        })

    # ---- codex (gpt-5.5) source-faithful vs source-free: the MODEL ABLATION. Source reveals the game's
    #      MECHANICS/win-condition (not the solution steps -- the agent still derives the action path);
    #      so the gap is the cost of DISCOVERING dynamics, not of planning steps. Both models near-parity
    #      WITH source; source-free, the Claude agent holds far more than codex.
    cf = jload("codex_full_game.json")
    agc = jload("agent_full_game.json")        # Claude source-assisted per-game (head-to-head)
    if cf:
        cx_full = sum(1 for v in cf.values() if v.get("full"))
        cx_levels = sum(v.get("levels", 0) for v in cf.values())
        cx_total = sum(v.get("win", 0) for v in cf.values())
        cx_model = sorted({v.get("model", "") for v in cf.values()})[-1]
        ncmds = [v.get("n_cmds", 0) for v in cf.values() if v.get("n_cmds")]
        macros.update({
            "ArcCodexFaithfulFull": str(cx_full),
            "ArcCodexFaithfulLevels": str(cx_levels),
            # ---- Claude-vs-Codex source-ASSISTED head-to-head (both read game source) ----
            "ArcCodexFullGames": str(cx_full),                 # 24/25 full
            "ArcCodexUnionGames": str(len(cf)),                # 25 games
            "ArcCodexLevels": str(cx_levels),                  # 182 levels
            "ArcCodexTotalLevels": str(cx_total),              # 183 possible
            "ArcCodexModel": cx_model or "gpt-5.5",
            "ArcCodexLfTwoLevels": str(cf.get("lf52", {}).get("levels", 0)),   # codex lf52 depth (9)
            "ArcCodexLfTwoWin": str(cf.get("lf52", {}).get("win", 0)),         # lf52 total levels (10)
            "ArcCodexCmdLo": str(min(ncmds) if ncmds else 0),  # command-efficiency range
            "ArcCodexCmdHi": str(max(ncmds) if ncmds else 0),
        })
        if agc:
            cpg = agc.get("per_game", {})
            macros["ArcClaudeLfTwoLevels"] = str(cpg.get("lf52", {}).get("levels", 0))  # claude lf52 depth (6)
            codex_head_to_head_assets(cpg, cf)
    csf = jload("arc3_fullgame_sourcefree_codex.json")
    if csf:
        pg = csf.get("per_game", csf)
        macros.update({
            "ArcCodexFreeFull": str(sum(1 for v in pg.values() if isinstance(v, dict)
                                        and v.get("win") and v.get("levels", 0) >= v.get("win", 99))),
            "ArcCodexFreeLevels": str(sum(v.get("levels", 0) for v in pg.values() if isinstance(v, dict))),
            "ArcCodexFreeGames": str(len(pg)),
        })


    # ---- E99 solve sweep (the successful directed-search approach) ----
    sweep=jload("e99_deep_sweep.json")
    if sweep:
        sg=sorted(sweep.get("solved",[]))
        seqs={g:sweep["results"][g].get("sequence") for g in sg if sweep["results"].get(g,{}).get("sequence")}
        macros.update({
            "ArcNSolved": str(len(sg)),
            "ArcSolvedList": ", ".join(f"\\texttt{{{g}}}" for g in sg),
            "ArcSeqLenRange": f"{min(len(x) for x in seqs.values())}--{max(len(x) for x in seqs.values())}" if seqs else "?",
        })

    # ---- Full-game solving result (the SOTA headline): read the source-of-truth JSON ----
    fg = jload("arc3_fullgame.json")
    if fg:
        gms = fg["games"]
        full = sorted(g for g, d in gms.items() if d.get("full"))
        partial = sorted((g for g, d in gms.items() if not d.get("full")),
                         key=lambda g: (-(gms[g]["levels"] or 0), g))
        macros.update({
            "ArcFullGames": str(fg["n_full"]),
            "ArcPartialGames": str(fg["n_partial"]),
            "ArcUnionGames": str(fg["n_games"]),
            "ArcFullLevels": str(fg["levels_completed"]),
            "ArcTotalLevels": str(fg["levels_total"]),
            "ArcFullPct": pct(fg["n_full"] / fg["n_games"]),
            "ArcLevelsPct": pct(fg["levels_completed"] / fg["levels_total"]),
            "ArcBaselineFull": str(fg["baseline1_full"]),
            "ArcPartialList": ", ".join(
                f"\\texttt{{{g}}}~({gms[g]['levels']}/{gms[g]['win']})" for g in partial),
        })

    # ---- Source-FREE result (process-isolated SandboxGame, NO game source; audited-clean + replay-verified
    #      + OpenWorld round-trip): the honest, harder protocol. The gap to source-faithful = cost of discovery.
    sfg = jload("arc3_fullgame_sourcefree.json")
    if sfg and fg:
        sf = sfg["per_game"]
        sf_full = sorted(sfg.get("full_games") or [g for g, d in sf.items()
                                                   if d.get("win") and d.get("levels", 0) >= d.get("win", 99)])
        macros.update({
            "ArcSFGames": str(sfg["n_full_games"]),
            "ArcSFLevels": str(sfg["total_levels"]),
            "ArcSFLevelsPct": pct(sfg["total_levels"] / sfg["total_possible"]),
            "ArcSFList": ", ".join(f"\\texttt{{{g}}}" for g in sf_full),
            "ArcSourceGapGames": str(fg["n_full"] - sfg["n_full_games"]),
            "ArcSourceGapLevels": str(fg["levels_completed"] - sfg["total_levels"]),
        })

    NUMS.write_text("% auto-generated by scripts/make_arc3_assets.py -- do not edit\n"
                    + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items()))
    print("wrote", NUMS.name, "|", macros)

    if fg:
        fullgame_assets(fg)
        if sfg:
            source_matrix_assets(fg, sfg)

    # ---- E120 action-efficiency (official RHAE-style score) ----
    rh = jload("arc3_rhae.json")
    if rh:
        rhae_assets(rh)
        NUMS.write_text(NUMS.read_text()
                        + f"\\newcommand{{\\ArcRhaeMean}}{{{rh['mean_score']:.1f}}}\n"
                        + f"\\newcommand{{\\ArcRhaeAboveHuman}}{{{rh['n_above_human']}}}\n"
                        + f"\\newcommand{{\\ArcRhaeAboveBaseline}}{{{rh['n_above_baseline1']}}}\n"
                        + f"\\newcommand{{\\ArcRhaeBaselineOne}}{{{rh['baseline1_rhae']}}}\n"
                        + f"\\newcommand{{\\ArcRhaeN}}{{{rh['n_scored']}}}\n")
        print("appended RHAE macros")

    # ---- source-free RHAE (E141): efficiency of the audited source-free solves vs the human baseline ----
    rsf = jload("e141_rhae_sourcefree.json")
    if rsf:
        capped = str(rsf["per_level_at_human_cap"]).split("/")
        NUMS.write_text(NUMS.read_text()
                        + f"\\newcommand{{\\ArcRhaeSFGame}}{{{rsf['per_game_official_style_mean']:.1f}}}\n"
                        + f"\\newcommand{{\\ArcRhaeSFPerLevel}}{{{rsf['per_level_efficiency_mean']:.1f}}}\n"
                        + f"\\newcommand{{\\ArcRhaeSFLevelsCapped}}{{{capped[0]}}}\n"
                        + f"\\newcommand{{\\ArcRhaeSFNLevels}}{{{rsf['n_levels_scored']}}}\n")
        print("appended source-free RHAE macros")

    # ---- E121 OpenWorld round-trip (each solve re-verified through a World) ----
    ow = jload("arc3_openworld_roundtrip.json")
    if ow:
        n_indexed = sum(1 for v in ow["games"].values() if v.get("indexed_fallback"))
        NUMS.write_text(NUMS.read_text()
                        + f"\\newcommand{{\\ArcOWVerified}}{{{ow['n_pass']}}}\n"
                        + f"\\newcommand{{\\ArcOWTotal}}{{{ow['n_total']}}}\n"
                        + f"\\newcommand{{\\ArcOWIndexed}}{{{n_indexed}}}\n")
        print(f"appended OpenWorld round-trip macros ({ow['n_pass']}/{ow['n_total']})")

    # ---- Leak-channel audit (scripts/audit_network_tools.py): did any source-free run reach the
    #      internet or call a web tool? Scans every captured Claude-arm (opus+fable) transcript's tool
    #      calls + every Bash command for network activity. Clean == the leak channel was unused. ----
    ta = jload("arc3_tool_audit.json")
    if ta:
        scanned = sum(a["transcripts"] for a in ta.get("arms", {}).values())
        bashcmds = f"{ta['n_bash_commands']:,}".replace(",", "{,}")   # LaTeX thousands
        NUMS.write_text(NUMS.read_text()
                        + f"\\newcommand{{\\ArcAuditTranscripts}}{{{scanned}}}\n"
                        + f"\\newcommand{{\\ArcAuditBashCmds}}{{{bashcmds}}}\n"
                        + f"\\newcommand{{\\ArcAuditNetHits}}{{{ta['network_hits']}}}\n"
                        + f"\\newcommand{{\\ArcAuditWebCalls}}{{{ta['web_tool_calls']}}}\n")
        print(f"appended leak-audit macros (transcripts={scanned}, net={ta['network_hits']}, web={ta['web_tool_calls']})")

    # figure: capability ladder (mean fidelity bars) + per-game Claude-vs-qwen32B scatter
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    BLUE, OCHRE, TEAL = "#1f4e79", "#c8881f", "#2a8a7f"
    fig, (axb, axs) = plt.subplots(1, 2, figsize=(9.2, 3.7))

    axb.bar([0, 1, 2], [q7_real, q32_real, cl_real], color=[OCHRE, OCHRE, BLUE], width=0.62)
    for i, v in enumerate([q7_real, q32_real, cl_real]):
        axb.text(i, v + 0.012, f"{100 * v:.0f}%", ha="center", fontsize=10, fontweight="bold")
    axb.set_xticks([0, 1, 2]); axb.set_xticklabels(["qwen-7B", "qwen-32B", "Claude"])
    axb.set_ylabel("verified-code fidelity (held-out exact-match)")
    axb.set_ylim(0, max(cl_real + 0.12, 0.3))
    axb.set_title(f"Synthesizer capability decides fidelity\n({len(real)} real-dynamics games)", fontsize=9.5)
    axb.grid(axis="y", alpha=0.25)

    gx = [g for g in real if g in q32]
    xs = [q32[g]["verified_exact"] for g in gx]
    ys = [cl[g]["verified_exact"] for g in gx]
    axs.scatter(xs, ys, color=TEAL, s=34, zorder=3, edgecolor="white", linewidth=0.6)
    axs.plot([0, 1], [0, 1], "--", color="black", alpha=0.4, lw=1)
    axs.set_xlabel("qwen-32B fidelity"); axs.set_ylabel("Claude fidelity")
    axs.set_xlim(-0.03, 1.03); axs.set_ylim(-0.03, 1.03)
    axs.set_title("Per-game: Claude vs qwen-32B\n(above diagonal = Claude better)", fontsize=9.5)
    axs.grid(alpha=0.25)

    fig.tight_layout()
    fig.savefig(FIGS / "arc3_fidelity.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("wrote", (FIGS / "arc3_fidelity.png").name)


if __name__ == "__main__":
    main()
