"""Generate experiments/MANIFEST.md from the scripts and cached results.

One row per experiment: its generating script, whether it is deterministic-offline
or Ollama-dependent, the model ids that appear in its result JSON, and provenance
(live run vs frozen artifact). Run: python3 scripts/make_manifest.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXP = ROOT / "experiments"
RESULTS = EXP / "results"
MODEL_RE = re.compile(r"^[a-z][a-z0-9._-]*:[0-9][0-9.]*b$")


def models_in(obj, acc):
    if isinstance(obj, str):
        if MODEL_RE.match(obj):
            acc.add(obj)
    elif isinstance(obj, dict):
        for v in obj.values():
            models_in(v, acc)
    elif isinstance(obj, list):
        for v in obj:
            models_in(v, acc)
    return acc


def main():
    rows = []
    for jf in sorted(RESULTS.glob("*.json")):
        name = jf.stem
        data = json.loads(jf.read_text())
        script = EXP / f"{name}.py"
        has_script = script.exists()
        src = script.read_text() if has_script else ""
        ollama = ("require_ollama" in src) or ("OllamaLLM" in src) or bool(models_in(data, set()))
        mode = "Ollama" if ollama else "offline"
        mods = sorted(models_in(data, set())) or ["--"]
        prov = data.get("provenance", "live run")
        if len(prov) > 70:
            prov = prov[:67] + "..."
        rows.append((name, "yes" if has_script else "NO", mode, ", ".join(mods), prov))

    n_off = sum(1 for r in rows if r[2] == "offline")
    lines = [
        "# Experiment manifest",
        "",
        "Auto-generated by `scripts/make_manifest.py` from `experiments/*.py` and "
        "`experiments/results/*.json`. Do not edit by hand.",
        "",
        f"- **{len(rows)}** experiments; **{n_off}** deterministic-offline, "
        f"**{len(rows) - n_off}** Ollama-dependent.",
        "- *Offline* experiments reproduce bit-for-bit. *Ollama* experiments reproduce "
        "in distribution (Metal is not bit-deterministic at fixed seed); rows whose "
        "provenance names a frozen artifact cite pinned dataset/model snapshots.",
        "",
        "| Experiment | Script | Mode | Models | Provenance |",
        "|---|---|---|---|---|",
    ]
    for name, sc, mode, mods, prov in rows:
        lines.append(f"| `{name}` | {sc} | {mode} | {mods} | {prov} |")
    (EXP / "MANIFEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote experiments/MANIFEST.md: {len(rows)} experiments "
          f"({n_off} offline, {len(rows) - n_off} Ollama)")


if __name__ == "__main__":
    main()
