"""ARC-AGI-3 paper assets (E86): reads experiments/results/arc3_{claude,qwen32b,qwen7b}/*.json and
writes papers/arc-3/arc3_numbers.tex + papers/assets/figs/arc3_fidelity.png. Single source of truth
for the arc-3 paper's numbers (do not hand-edit arc3_numbers.tex).

  python scripts/make_arc3_assets.py
"""
import glob
import json
import statistics as st
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "experiments" / "results"
FIGS = ROOT / "papers" / "assets" / "figs"
NUMS = ROOT / "papers" / "arc-3" / "arc3_numbers.tex"


def load(sub):
    out = {}
    for f in glob.glob(str(RES / sub / "*.json")):
        d = json.load(open(f))
        out[d["game"]] = d
    return out


def main():
    cl, q32, q7 = load("arc3_claude"), load("arc3_qwen32b"), load("arc3_qwen7b")

    excluded = sorted(g for g, d in cl.items() if d.get("transitions") == 0)
    done = {g: d for g, d in cl.items() if d.get("verified_exact") is not None}
    trivial = sorted(g for g, d in done.items() if d.get("copy_frame_exact", 0) >= 0.99)
    real = sorted(g for g, d in done.items() if g not in trivial)

    def fid(store, games):
        xs = [store[g]["verified_exact"] for g in games
              if g in store and store[g].get("verified_exact") is not None]
        return st.mean(xs) if xs else 0.0

    cl_real = fid(cl, real)
    q32_real = fid(q32, [g for g in real if g in q32])
    q7_real = fid(q7, [g for g in real if g in q7])

    beats_copy = sum(cl[g]["verified_exact"] - cl[g].get("copy_frame_exact", 0) > 0.01 for g in real)
    beats_q32 = sum(cl[g]["verified_exact"] > (q32.get(g, {}).get("verified_exact") or 0)
                    for g in real if g in q32)
    n_q32 = sum(1 for g in real if g in q32)
    lift = st.mean(cl[g]["verified_exact"] - cl[g].get("copy_frame_exact", 0) for g in real)
    near = sorted((g for g in real if cl[g]["verified_exact"] >= 0.9), key=lambda g: -cl[g]["verified_exact"])
    det_all = all(d.get("replay_determinism") == 1.0 for d in done.values() if d.get("replay_determinism") is not None)

    def pct(x):
        return f"{round(100 * x)}\\%"

    macros = {
        "ArcNGames": str(len(cl)),
        "ArcNDone": str(len(done)),
        "ArcNReal": str(len(real)),
        "ArcNTrivial": str(len(trivial)),
        "ArcNExcluded": str(len(excluded)),
        "ArcClaudeFid": pct(cl_real),
        "ArcQwenThirtyTwoFid": pct(q32_real),
        "ArcQwenSevenFid": pct(q7_real),
        "ArcClaudeBeatsCopy": str(beats_copy),
        "ArcClaudeBeatsQwen": str(beats_q32),
        "ArcRealForQwen": str(n_q32),
        "ArcClaudeLift": pct(lift),
        "ArcNNearPerfect": str(len(near)),
        "ArcDeterminismAll": "1.00" if det_all else "<1.00",
    }
    NUMS.write_text("% auto-generated by scripts/make_arc3_assets.py -- do not edit\n"
                    + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in macros.items()))
    print("wrote", NUMS.name, "|", macros)

    # figure: capability ladder (mean fidelity bars) + per-game Claude-vs-qwen32B scatter
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    BLUE, OCHRE, TEAL = "#1f4e79", "#c8881f", "#2a8a7f"
    fig, (axb, axs) = plt.subplots(1, 2, figsize=(9.2, 3.7))

    axb.bar([0, 1, 2], [q7_real, q32_real, cl_real], color=[OCHRE, OCHRE, BLUE], width=0.62)
    for i, v in enumerate([q7_real, q32_real, cl_real]):
        axb.text(i, v + 0.012, f"{100 * v:.0f}%", ha="center", fontsize=10, fontweight="bold")
    axb.set_xticks([0, 1, 2]); axb.set_xticklabels(["qwen-7B", "qwen-32B", "Claude"])
    axb.set_ylabel("verified-code fidelity (held-out exact-match)")
    axb.set_ylim(0, max(cl_real + 0.12, 0.3))
    axb.set_title(f"Synthesizer capability decides fidelity\n({len(real)} real-dynamics games)", fontsize=9.5)
    axb.grid(axis="y", alpha=0.25)

    gx = [g for g in real if g in q32]
    xs = [q32[g]["verified_exact"] for g in gx]
    ys = [cl[g]["verified_exact"] for g in gx]
    axs.scatter(xs, ys, color=TEAL, s=34, zorder=3, edgecolor="white", linewidth=0.6)
    axs.plot([0, 1], [0, 1], "--", color="black", alpha=0.4, lw=1)
    axs.set_xlabel("qwen-32B fidelity"); axs.set_ylabel("Claude fidelity")
    axs.set_xlim(-0.03, 1.03); axs.set_ylim(-0.03, 1.03)
    axs.set_title("Per-game: Claude vs qwen-32B\n(above diagonal = Claude better)", fontsize=9.5)
    axs.grid(alpha=0.25)

    fig.tight_layout()
    fig.savefig(FIGS / "arc3_fidelity.png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("wrote", (FIGS / "arc3_fidelity.png").name)


if __name__ == "__main__":
    main()
